In [ ]:
!wget -q https://github.com/PSAM-5020-2026S-A/5020-utils/raw/main/src/data_utils.py

In [ ]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
from sklearn.feature_extraction import text as sklearn_text

import numpy as np
import pandas as pd
import spacy
import torch.nn.functional as F
import torch
import umap
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import textwrap
from tqdm.notebook import tqdm
import re
import json

from google.colab import files
from data_utils import balance_score, distance_score, silhouette_score, display_silhouette_plots

# Load data and initialize model

In [ ]:
# load data
artists_df = pd.read_csv('./artists.csv')
exhibitions_df = pd.read_csv('./exhibitions.csv')

artist_texts_df = pd.read_csv('./all_artist_texts.csv')
institution_texts_df = pd.read_csv('./all_institution_texts.csv')

artworks_df = pd.read_csv('./artworks.csv')
institutions_df = pd.read_csv('./institutions.csv')

# rename unnamed index
artist_texts_df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
institution_texts_df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)

institution_texts_df.head()

   id  institution                 text source_idx  artist  is_artwork
0   0            0  American, born 1975       IT01       1       False
1   1            0             American       IT02       1       False
2   2            0               female       IT03       1       False
3   3            0  American, born 1975       IT04       2       False
4   4            0             American       IT05       2       False

In [ ]:
nlp = spacy.load("en_core_web_sm")
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)

if torch.cuda.is_available():
    print("using GPU")
    model.to('cuda')
else:
    print("using CPU")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/140 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

configuration_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- configuration_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- modeling_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/547M [00:00<?, ?B/s]

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

using GPU

# Text parsing helpers

*   semantic_chunk
*   get_word_weights
*   get_chunks_for_df

In [ ]:
def get_word_weights(doc, vectorizer, n=3):
  doc_tfidf = vectorizer.transform([doc])
  feature_names = vectorizer.get_feature_names_out()

  df = pd.DataFrame(doc_tfidf[0].T.todense(),
                    index=feature_names,
                    columns=["tfidf"])

  ret = df.sort_values(by="tfidf", ascending=False)

  return ret.head(n).index.tolist()

In [ ]:
def get_chunks_for_df(df, process_artworks, min_sentences=1, min_chars=100):
  chunks_arr = []

  # Add tqdm to the iterrows loop for a progress bar
  for idx, row in tqdm(df.iterrows(), total=len(df), desc="Chunking texts"):
    if (row["text"] is not None):
      if (row["is_artwork"] and not process_artworks):
        # skip processing for artwork titles
        chunks_arr.append({
            "source_idx": row["source_idx"],
            "text": row["text"],
            "is_artwork": row["is_artwork"]
        })
      else:
        chunks = semantic_chunk(row["text"], 0.75, min_sentences=min_sentences, min_chars=min_chars)
        for chunk in chunks:
            chunks_arr.append({
                "source_idx": row["source_idx"],
                "text": chunk,
                "is_artwork": row["is_artwork"]
            })


  chunks_df = pd.DataFrame(chunks_arr)
  return chunks_df

In [ ]:
def semantic_chunk(text, threshold=0.75, min_sentences=1, min_chars=100, max_sentences=3, max_chunk_chars=300):
    # replace double new lines with an explicit marker  to force a chunk split.
    processed_text = re.sub(r'\n\n+', '\n<PARAGRAPH_SPLIT_MARKER>\n', text)
    doc = nlp(processed_text)

    sentences_raw = [sent.text.strip() for sent in doc.sents if sent.text.strip()]

    if not sentences_raw:
        return []

    sentences_to_embed_flat = []
    original_idx_to_flat_indices = []

    current_flat_idx = 0
    for s_raw_text in sentences_raw:
        if '<PARAGRAPH_SPLIT_MARKER>' in s_raw_text:
            # if the sentence contains the marker, split it to extract actual text parts and discard the text
            parts = [p.strip() for p in s_raw_text.split('<PARAGRAPH_SPLIT_MARKER>') if p.strip()]
            if parts:
                original_idx_to_flat_indices.append((current_flat_idx, len(parts)))
                sentences_to_embed_flat.extend(parts)
                current_flat_idx += len(parts)
            else:
                original_idx_to_flat_indices.append((-1, 0))
        else:
            # add clean sentences to be embedded
            original_idx_to_flat_indices.append((current_flat_idx, 1))
            sentences_to_embed_flat.append(s_raw_text)
            current_flat_idx += 1

    if not sentences_to_embed_flat:
        return []

    embeddings_flat = model.encode(
        [f"search_document: {s}" for s in sentences_to_embed_flat],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    chunks = []
    current_chunk_sentences = []
    current_chunk_embeddings = []

    for i, sentence_raw_text in enumerate(sentences_raw):
        start_flat_idx, num_flat_sentences = original_idx_to_flat_indices[i]

        # for forced split points with no actual text
        if start_flat_idx == -1:
            if current_chunk_sentences:
                chunks.append(" ".join(current_chunk_sentences))
                current_chunk_sentences = []
                current_chunk_embeddings = []
            continue

        # iterate over extracted clean sentences
        for j in range(num_flat_sentences):
            sentence_to_process = sentences_to_embed_flat[start_flat_idx + j]
            embedding_to_process = embeddings_flat[start_flat_idx + j]

            prospective_chunk_len_sentences = len(current_chunk_sentences) + 1
            prospective_chunk_len_chars = sum(len(s) for s in current_chunk_sentences) + len(sentence_to_process)

            force_max_split = prospective_chunk_len_sentences > max_sentences or prospective_chunk_len_chars > max_chunk_chars

            semantically_different_split = False
            if current_chunk_sentences:
                current_char_count = sum(len(s) for s in current_chunk_sentences)
                meets_min_sentences_for_sem = len(current_chunk_sentences) >= min_sentences
                meets_min_chars_for_sem = current_char_count >= min_chars

                chunk_embedding = np.mean(current_chunk_embeddings, axis=0, keepdims=True)
                sim = cosine_similarity(chunk_embedding, embedding_to_process.reshape(1, -1))[0][0]
                semantically_different_split = sim < threshold and meets_min_sentences_for_sem and meets_min_chars_for_sem

            should_split = False
            if current_chunk_sentences and (force_max_split or semantically_different_split):
                should_split = True

            if should_split:
                chunks.append(" ".join(current_chunk_sentences))
                current_chunk_sentences = [sentence_to_process]
                current_chunk_embeddings = [embedding_to_process]
            else:
                current_chunk_sentences.append(sentence_to_process)
                current_chunk_embeddings.append(embedding_to_process)

    # finalize: merge trailing chunk backward if too short rather than discarding
    if current_chunk_sentences:
        leftover = " ".join(current_chunk_sentences)
        if len(leftover) < min_chars and chunks:
            chunks[-1] = chunks[-1] + " " + leftover
        else:
            chunks.append(leftover)

    # merge any short mid-stream chunks (e.g. from force splits) forward into the next
    result = []
    for chunk in chunks:
        if result and len(result[-1]) < min_chars:
            result[-1] = result[-1] + " " + chunk
        else:
            result.append(chunk)

    return [c for c in result if len(c) >= min_chars]

# Prep data

In [ ]:
# get all exhibition text
exhibitions_df['full_text'] = exhibitions_df['name'].fillna('') + ". " + exhibitions_df['description'].fillna('')

In [ ]:
# chunk artist texts
ar_texts = get_chunks_for_df(artist_texts_df, False, 2)

Chunking texts:   0%|          | 0/584 [00:00<?, ?it/s]

In [ ]:
print(len(ar_texts))
ar_texts.head()

7092

  source_idx                                               text  is_artwork
0       AT01  That’s a great question, but also a rabbit hol...       False
1       AT01  I wanted to directly challenge previous assert...       False
2       AT01  I think of my work as an organism that fluctua...       False
3       AT01  I’ve always been interested in the shared real...       False
4       AT01  In previous works, I mined the generic for fou...       False

In [ ]:
# chunk inst texts
inst_texts = get_chunks_for_df(institution_texts_df, True, 1, 0)

Chunking texts:   0%|          | 0/338 [00:00<?, ?it/s]

In [ ]:
print(len(inst_texts))
inst_texts.head()

1003

  source_idx                 text  is_artwork
0       IT01  American, born 1975       False
1       IT02             American       False
2       IT03               female       False
3       IT04  American, born 1975       False
4       IT05             American       False

# Labeling - stop words

In [ ]:
first_stop_words = ["biennale", "biennial", "museum", "exhibition", "baratta", "italian", "smithsonian", "hispanic", "year", "s", "art", "artist", "th", "arsenale", "tam", "don", "didn", "t", "identity", "ii", "kkk"]
# add more labels of things that are too specific or don't make sense with only one word
addl_stop_words = ["nuyorican", "francisco", "inhabit", "fourth", "just", "san", "work", "think", "just"]

new_stop_words = first_stop_words + addl_stop_words
custom_stop_words = list(sklearn_text.ENGLISH_STOP_WORDS.union(new_stop_words))

In [ ]:
# add all the artist first and last names to the stop words list
for idx, row in artists_df.iterrows():
    # split by first and last name
    names = re.split(r'[- ]', row["name"])

    for name in names:
      custom_stop_words.append(name.lower())

# add all locations
for idx, row in exhibitions_df.iterrows():
  locations = re.split(r'[, ]', row["location"])

  for location in locations:
    custom_stop_words.append(location.lower())

In [ ]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text.lower())

# Identity and self relevance queries
For filtering texts and prioritizing keywords

In [ ]:
query_words = [
    # original
    "identity", "persona", "race", "ethnicity", "culture",
    "self", "category", "belonging", "community",
    "ancestry", "generation", "experience", "in-between",

    # mixed race
    "mixed", "multiracial", "biracial", "half", "hyphenated",
    "passing", "blood", "skin", "contradict"

    # diaspora
    "diaspora", "diasporic", "transnational", "immigrant", "migration",
    "displacement", "exile", "homeland", "motherland", "origin",

    # in betweenness
    "liminal", "borderlands", "threshold", "assimilation", "integration",

    # heritage
    "heritage", "roots", "memory", "nostalgia", "home", "tradition",
    "language", "birth", "death", "born", "nationality", "died"

    # visibility
    "otherness", "outsider", "minority", "visibility", "authenticity",
    "representation", "erasure", "recognition", "voice", "truth",
    "invisible", "seen", "silence", "absence"
]

In [ ]:
# self relevance query to get first-person testimony about the artist's own experience rather than framing others
self_query = (
    "search_query: speaking in my own voice about who I am — "
    "my mixed heritage, my family's immigration story, growing up caught between cultures, "
    "and how my racial and ethnic identity lives in my body and my life"
)

# keyword sorting queries — split by concept so each gets equal weight when embeddings are averaged
keyword_sort_queries = [
    "search_query: words that might illustrate who someone is and what they identify as",
    "search_query: words that describe the experience of being in-between cultures or having a unique background that is hard to describe",
    "search_query: words that illustrate the concept of identity and creating a public image of that personal experience",
    "search_query: words that describe being mixed-race asian american and navigating multiple cultural frameworks",
]

keyword_sort_queries = [
    "search_query: who someone is, what they identify as, "
    "how they understand and present themselves based on their unique background",

    "search_query: being mixed, carrying more than one ethnic heritage, identifying with multiple cultures, "
    "having a multiracial background that defies traditional identity category labels, "
    "existing in-between cultures with immigration across generations",

    "search_query: identity as a personal experience, the public image of an "
    "interior cultural self, how one represents their identity publicly",

    "search_query: navigating multiple frameworks with a mixed race diasporic identity, "
    "moving between hyphenated identities, displacement and belonging across communities and nations",
]

In [ ]:
identity_query = "search_query: " + " ".join(query_words)
identity_query_embedding = model.encode(identity_query, convert_to_numpy=True, normalize_embeddings=True)

In [ ]:
# encode each concept query separately and average — gives equal weight to each
_kw_sort_vecs = model.encode(keyword_sort_queries, convert_to_numpy=True, normalize_embeddings=True)
keyword_sort_query_embedding = _kw_sort_vecs.mean(axis=0)
keyword_sort_query_embedding = keyword_sort_query_embedding / np.linalg.norm(keyword_sort_query_embedding)

# Exhibition labels

In [ ]:
all_corpus = exhibitions_df['full_text'].tolist()

vectorizer = TfidfVectorizer(preprocessor=remove_numbers, stop_words=custom_stop_words)

tfidf_matrix = vectorizer.fit_transform(all_corpus)

In [ ]:
# get word weights for each row in exhibitions
LABEL_CANDIDATES_N = 5

exhibitions_df["labels"] = exhibitions_df.apply(lambda row: get_word_weights(row['full_text'], vectorizer, n=LABEL_CANDIDATES_N), axis=1)
exhibitions_df["labels"]

0                     [hapa, ancestry, asian, pa, half]
1                   [mixed, asian, american, race, war]
2       [universe, citizen, life, integration, college]
3                  [orient, dis, asian, diaspora, shih]
4          [legacies, asian, american, political, city]
5                [east, chinese, asian, american, uovo]
6     [countries, international, world, okwui, edition]
7     [ideologies, global, authoritarian, fascisms, ...
8         [korean, english, pacific, western, cultural]
9         [hard, america, american, title, established]
10    [portraiture, asian, american, encounter, port...
11    [agency, ascendancy, personal, self, contempor...
12          [american, asian, chinese, references, way]
13    [decade, frameworks, studio, performance, issues]
14     [scratching, moon, asian, communities, american]
Name: labels, dtype: object

In [ ]:
LABEL_IDENTITY_THRESHOLD = 0.5
LABEL_TOP_N = 3

def sort_labels_by_identity(labels):
    kw_embeddings = model.encode(
        ["search_document: " + kw for kw in labels],
        convert_to_numpy=True, normalize_embeddings=True
    )
    sims = cosine_similarity([keyword_sort_query_embedding], kw_embeddings)[0]
    scored = sorted(zip(sims, labels), reverse=True)
    filtered = [(sim, kw) for sim, kw in scored if sim >= LABEL_IDENTITY_THRESHOLD]
    return [kw for _, kw in filtered[:LABEL_TOP_N]]

exhibitions_df["labels"] = exhibitions_df["labels"].apply(sort_labels_by_identity)
exhibitions_df["labels"]

0                 [ancestry, asian, hapa]
1                    [mixed, asian, race]
2            [integration, citizen, life]
3                  [diaspora, asian, dis]
4            [asian, american, political]
5              [chinese, asian, american]
6       [international, countries, world]
7     [ideologies, global, authoritarian]
8             [cultural, korean, pacific]
9        [american, america, established]
10        [portraits, portraiture, asian]
11         [self, contemporary, personal]
12             [chinese, asian, american]
13      [performance, frameworks, studio]
14         [asian, american, communities]
Name: labels, dtype: object

In [ ]:
# download w labels
exhibitions_df.to_csv('exhibitions_with_labels.csv', index=False)

files.download('exhibitions_with_labels.csv')

# Filter for identity-specific texts

For artists

In [ ]:
# density of first person words to filter for speaking about self
def _fp_density(text):
    words = re.findall(r'\b\w+\b', text.lower())
    fp = sum(1 for w in words if w in {'i', 'me', 'my', 'mine', 'myself'})
    return fp / max(len(words), 1)

In [ ]:
chunk_embeddings_for_filter = model.encode(
    ["search_document: " + t for t in ar_texts["text"]],
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/222 [00:00<?, ?it/s]

In [ ]:
# get identity relevance first
ar_texts["identity_relevance"] = cosine_similarity([identity_query_embedding], chunk_embeddings_for_filter)[0]

# get self relevance
self_query_embedding = model.encode(self_query, convert_to_numpy=True, normalize_embeddings=True)
ar_texts["self_relevance"] = cosine_similarity([self_query_embedding], chunk_embeddings_for_filter)[0]

# first person density words to tiebreak in some cases
ar_texts["fp_density"] = ar_texts["text"].apply(_fp_density)
fp_norm_cap = 0.15
ar_texts["fp_density_norm"] = (ar_texts["fp_density"] / fp_norm_cap).clip(upper=1.0)

# weigh priority
ar_texts["priority_score"] = (
    ar_texts["identity_relevance"] * 0.35
    + ar_texts["self_relevance"]   * 0.55
    + ar_texts["fp_density_norm"]  * 0.10
)

# per-artist floor + ceiling using priority score
THRESHOLD = 0.6   # for identity_relevance to filter to topic
MIN_QUOTES = 3
MAX_QUOTES = 12

source_to_artist = artist_texts_df.set_index('source_idx')['artist'].to_dict()
ar_texts['artist_id'] = ar_texts['source_idx'].map(source_to_artist)

def filter_artist_quotes(group):
    above = group[group['identity_relevance'] >= THRESHOLD]
    if len(above) >= MIN_QUOTES:
        return above.nlargest(MAX_QUOTES, 'priority_score')
    else:
        return group.nlargest(MIN_QUOTES, 'priority_score')

non_artwork = ar_texts[ar_texts['is_artwork'] == False]
artworks    = ar_texts[ar_texts['is_artwork'] == True]

filtered_text = non_artwork.groupby('artist_id', group_keys=False).apply(filter_artist_quotes)
filtered_ar_texts = pd.concat([filtered_text, artworks]).reset_index(drop=True)

print(f"Rows remaining: {len(filtered_ar_texts)}")
print(f"\nArtist text chunks per artist:\n{filtered_text.groupby('artist_id').size().sort_values()}")

Rows remaining: 614

Artist text chunks per artist:
artist_id
0      3
1      3
5      3
8      3
10     3
12     3
19     3
17     3
27     3
21     3
28     3
29     4
6      4
25     4
2      4
13     5
26     7
16     7
24    10
7     11
3     12
4     12
9     12
11    12
15    12
14    12
20    12
18    12
23    12
22    12
dtype: int64

/tmp/ipykernel_10012/771909683.py:38: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  filtered_text = non_artwork.groupby('artist_id', group_keys=False).apply(filter_artist_quotes)

In [ ]:
texts_only = filtered_ar_texts[filtered_ar_texts["is_artwork"] == False]
texts_only.to_csv('ar_texts_filtered.csv', index=False)
# files.download('ar_texts_filtered.csv')

For institutions

In [ ]:
inst_chunk_embeddings_for_filter = model.encode(
      ["search_document: " + t for t in inst_texts["text"]],
      convert_to_numpy=True,
      normalize_embeddings=True,
      show_progress_bar=True
  )

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

In [ ]:
# reuses identity_query_embedding already computed in the artist filter above
inst_texts["identity_relevance"] = cosine_similarity(
    [identity_query_embedding], inst_chunk_embeddings_for_filter
)[0]

In [ ]:
INST_ARTWORK_THRESHOLD = 0.5
INST_MIN_TEXTS = 3
INST_MIN_PER_INSTITUTION = 2   # min non-artwork texts to keep per institution
INST_MAX_PER_INSTITUTION = 6   # max non-artwork texts to keep per institution
INST_MAX_ART_TEXTS = 24        # cap for artwork texts per artist

source_to_artist_inst = institution_texts_df.set_index('source_idx')['artist'].to_dict()
source_to_institution_inst = institution_texts_df.set_index('source_idx')['institution'].to_dict()

inst_texts['artist_id'] = inst_texts['source_idx'].map(source_to_artist_inst)
inst_texts['institution_id'] = inst_texts['source_idx'].map(source_to_institution_inst)

In [ ]:
def filter_inst_texts(group):
    non_art = group[group['is_artwork'] == False]
    art     = group[group['is_artwork'] == True]

    # take between INST_MIN_PER_INSTITUTION and INST_MAX_PER_INSTITUTION texts per institution
    non_art_capped = (
        non_art
        .sort_values('identity_relevance', ascending=False)
        .groupby('institution_id', group_keys=False)
        .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
    )

    # one chunk per artwork: keep highest identity_relevance chunk per source_idx
    art_deduped = art.loc[art.groupby('source_idx')['identity_relevance'].idxmax()] if len(art) > 0 else art

    # apply threshold to deduped artworks; pad to floor if not enough pass
    art_above = art_deduped[art_deduped['identity_relevance'] >= INST_ARTWORK_THRESHOLD]
    if len(art_above) < INST_MIN_TEXTS and len(art_deduped) > 0:
        n_needed = INST_MIN_TEXTS - len(art_above)
        art_pad  = art_deduped[art_deduped['identity_relevance'] < INST_ARTWORK_THRESHOLD].nlargest(n_needed, 'identity_relevance')
        kept_art = pd.concat([art_above, art_pad])
    else:
        kept_art = art_above

    art_capped = kept_art.nlargest(INST_MAX_ART_TEXTS, 'identity_relevance')

    return pd.concat([non_art_capped, art_capped])

In [ ]:
filtered_inst_texts = (
    inst_texts
    .groupby('artist_id', group_keys=False)
    .apply(filter_inst_texts, include_groups=False)
    .reset_index(drop=True)
)

filtered_inst_texts['artist_id'] = filtered_inst_texts['source_idx'].map(source_to_artist_inst)

print(f"before: {len(inst_texts)}")
print(f"After filter: {len(filtered_inst_texts)} rows")
print(f"\nInst chunks per artist:\n{filtered_inst_texts.groupby('artist_id').size().sort_values()}")

before: 1003
After filter: 350 rows

Inst chunks per artist:
artist_id
24     2
20     2
18     2
26     2
17     2
1      3
15     3
3      3
7      4
11     5
4      6
14     6
2      6
16     7
23     7
19     7
27     7
28     7
13    11
9     12
6     12
12    13
10    19
8     21
29    21
22    23
25    24
21    29
5     38
0     46
dtype: int64

/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])
/tmp/ipykernel_10012/357213564.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[:max(INST_MIN_PER_INSTITUTION, min(INST_MAX_PER_INSTITUTION, len(g)))])

In [ ]:
inst_texts = filtered_inst_texts

# Embed all texts

For artists

In [ ]:
ar_texts = filtered_ar_texts

In [ ]:
ar_texts_arr = ["clustering: " + t for t in ar_texts["text"].tolist()]

# embed
ar_embeddings = model.encode(
    ar_texts_arr,
    batch_size=64,
    convert_to_tensor=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

ar_embeddings_np = ar_embeddings.cpu().numpy()

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

For institutions

In [ ]:
inst_texts_arr = ["clustering: " + t for t in inst_texts["text"].tolist()]

# embed
inst_embeddings = model.encode(
    inst_texts_arr,
    batch_size=64,
    convert_to_tensor=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

inst_embeddings_np = inst_embeddings.cpu().numpy()

Batches:   0%|          | 0/6 [00:00<?, ?it/s]

# Build lookups

In [ ]:
artist_texts_source_idx_map = artist_texts_df.set_index('source_idx')
institution_texts_source_idx_map = institution_texts_df.set_index('source_idx')

artworks_source_idx_map = artworks_df.set_index('id')

In [ ]:
def map_metadata(row, mode):
    artist_id = np.nan
    institution_id = np.nan

    if mode == 'artist':
      source_idx_map = artist_texts_source_idx_map
    else:
      source_idx_map = institution_texts_source_idx_map

    if row['is_artwork']:
        artwork_row = artworks_source_idx_map.loc[row['source_idx']]
        artist_id = artwork_row['artist']
        institution_id = artwork_row['institution']
    else:
        artist_id = source_idx_map.loc[row['source_idx'], 'artist']
        if mode != 'artist':
          institution_id = source_idx_map.loc[row['source_idx'], 'institution']

    return pd.Series({'artist_id': artist_id, 'institution_id': institution_id})

In [ ]:
artist_id_to_name = artists_df.set_index("id")["name"].to_dict()
inst_id_to_name = institutions_df.set_index("id")["name"].to_dict()

ar_lookup_df = ar_texts[["text", "source_idx", "is_artwork"]].copy()

ar_lookup_df[['artist_id', 'institution_id']] = ar_lookup_df.apply(lambda x: map_metadata(x, 'artist'), axis=1)

ar_lookup_df['artist_id'] = ar_lookup_df['artist_id'].astype(pd.Int64Dtype())
ar_lookup_df['institution_id'] = ar_lookup_df['institution_id'].astype(pd.Int64Dtype())

# for testing, map to names to see accuracy
ar_lookup_df['artist_name'] = ar_lookup_df['artist_id'].map(artist_id_to_name)
ar_lookup_df['institution_name'] = ar_lookup_df['institution_id'].map(inst_id_to_name)

ar_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"So, I’m still a struggling artist—at least in ...",AT53,False,0,<NA>,Isamu Noguchi,NaN
1,So I don’t have much faith in myself as a kind...,AT54,False,0,<NA>,Isamu Noguchi,NaN
2,"… You got to take my integrity, you know, as m...",AT56,False,0,<NA>,Isamu Noguchi,NaN
3,I think one of the things that’s interesting f...,AT02,False,1,<NA>,Amanda Ross-Ho,NaN
4,Navigating this stuff allows me to investigate...,AT01,False,1,<NA>,Amanda Ross-Ho,NaN
...,...,...,...,...,...,...,...
609,Belly Painting: Prussian Blue,W405,True,12,7,Byron Kim,National Gallery of Art
610,Untitled,W406,True,29,7,Hung Liu,National Gallery of Art
611,Post-Age,W407,True,29,7,Hung Liu,National Gallery of Art
612,Seoul Home – Inverted,W408,True,6,7,Do Ho Suh,National Gallery of Art
613,Prison Bunk Beds,W409,True,10,7,Martin Wong,National Gallery of Art

In [ ]:
inst_lookup_df = inst_texts[["text", "source_idx", "is_artwork"]].copy()

inst_lookup_df[['artist_id', 'institution_id']] = inst_lookup_df.apply(lambda x: map_metadata(x, 'institution'), axis=1)

inst_lookup_df['artist_id'] = inst_lookup_df['artist_id'].astype(pd.Int64Dtype())
# inst_lookup_df['institution_id'] = inst_lookup_df['institution_id'].astype(pd.Int64Dtype())

# add names for testing
inst_lookup_df['artist_name'] = inst_lookup_df['artist_id'].map(artist_id_to_name)
inst_lookup_df['institution_name'] = inst_lookup_df['institution_id'].map(inst_id_to_name)

inst_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"American, 1904–1988",IT16,False,0,0,Isamu Noguchi,Museum of Modern Art
1,His encounter with the organic shapes (or “bio...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
2,"[noꜜgɯtɕi isamɯ], English: ; November 17, 1904...",IT18,False,0,1,Isamu Noguchi,Whitney Museum of American Art
3,Noguchi’s interpenetrating sculptures—made in ...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
4,The result suggests a state of precariousness;...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
...,...,...,...,...,...,...,...
345,The juxtaposition of familiar shapes suggests ...,W406,True,29,7,Hung Liu,National Gallery of Art
346,Faded pink oval portrait of a young woman surr...,W280,True,29,0,Hung Liu,Museum of Modern Art
347,Portrait of a young woman in an oval frame wit...,W281,True,29,0,Hung Liu,Museum of Modern Art
348,Chart of drawn facial features and nose shapes...,W278,True,29,0,Hung Liu,Museum of Modern Art
349,Large painting showing a leaping horse with a ...,W279,True,29,0,Hung Liu,Museum of Modern Art

In [ ]:
inst_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"American, 1904–1988",IT16,False,0,0,Isamu Noguchi,Museum of Modern Art
1,His encounter with the organic shapes (or “bio...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
2,"[noꜜgɯtɕi isamɯ], English: ; November 17, 1904...",IT18,False,0,1,Isamu Noguchi,Whitney Museum of American Art
3,Noguchi’s interpenetrating sculptures—made in ...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
4,The result suggests a state of precariousness;...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
...,...,...,...,...,...,...,...
345,The juxtaposition of familiar shapes suggests ...,W406,True,29,7,Hung Liu,National Gallery of Art
346,Faded pink oval portrait of a young woman surr...,W280,True,29,0,Hung Liu,Museum of Modern Art
347,Portrait of a young woman in an oval frame wit...,W281,True,29,0,Hung Liu,Museum of Modern Art
348,Chart of drawn facial features and nose shapes...,W278,True,29,0,Hung Liu,Museum of Modern Art
349,Large painting showing a leaping horse with a ...,W279,True,29,0,Hung Liu,Museum of Modern Art

# Helpers to cluster for n

In [ ]:
def run_clustering_and_evaluate(embeddings, n_clusters, sample_weight=None):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init="auto")
    cluster_labels = kmeans.fit_predict(embeddings, sample_weight=sample_weight)

    sc = kmeans.score(embeddings, sample_weight=sample_weight)
    distance_sc = distance_score(embeddings, cluster_labels)
    silhouette_sc = silhouette_score(embeddings, cluster_labels)
    balance_sc = balance_score(cluster_labels)

    print(f"\n{'='*80}")
    print(f"FOR NUM CLUSTERS {n_clusters} --------------------")
    print("score: ", sc)
    print("distance score: ", distance_sc)
    print("silhouette score: ", silhouette_sc)
    print("balance score: ", balance_sc)

    return kmeans, cluster_labels

In [ ]:
def calculate_distances(embeddings_np, kmeans):
    centers = kmeans.cluster_centers_
    all_distances = euclidean_distances(embeddings_np, centers)

    return all_distances

In [ ]:
def extract_cluster_keywords(df_source, cluster_labels, n_clusters, stop_words):
      temp_df = df_source.copy()
      temp_df["cluster"] = cluster_labels
      cluster_texts = []
      for c in range(n_clusters):
          mask = temp_df["cluster"] == c
          combined = " ".join(temp_df.loc[mask, "text"].tolist())
          cluster_texts.append(combined)
      vectorizer = TfidfVectorizer(preprocessor=remove_numbers, stop_words=stop_words, token_pattern=r'\b\w*[a-zA-Z]\w*\b', max_features=1000, ngram_range=(1,1))
      tfidf_matrix = vectorizer.fit_transform(cluster_texts)
      feature_names = vectorizer.get_feature_names_out()
      candidate_n = 10
      cluster_keywords = {}
      for c in range(n_clusters):
          row = tfidf_matrix[c].toarray()[0]
          max_tfidf = row.max() if row.max() > 0 else 1.0
          top_indices = np.argsort(row)[::-1][:candidate_n]
          keywords = [feature_names[i] for i in top_indices]
          tfidf_scores = [float(row[i]) / max_tfidf for i in top_indices]
          kw_embeddings = model.encode(
              ["search_document: " + kw for kw in keywords],
              convert_to_numpy=True, normalize_embeddings=True
          )
          kw_sims = cosine_similarity([keyword_sort_query_embedding], kw_embeddings)[0]
          sorted_kws = sorted(zip(kw_sims, keywords, tfidf_scores), reverse=True)
          cluster_keywords[str(c)] = [
              {"word": kw, "relevance_score": round(float(sim), 4), "tfidf_score": round(tfidf, 4)}
              for sim, kw, tfidf in sorted_kws
          ]

      return cluster_keywords

In [ ]:
def get_cluster_results_df(df_source, cluster_labels, all_distances, n_clusters):
    own_center_distances = all_distances[range(len(cluster_labels)), cluster_labels]

    masked = all_distances.copy()
    masked[range(len(cluster_labels)), cluster_labels] = np.inf
    closest_other_cluster = np.argmin(masked, axis=1)
    closest_other_cluster_distance = masked[range(len(cluster_labels)), closest_other_cluster]

    results_df = pd.DataFrame({
        "point":                 range(len(cluster_labels)),
        "cluster":               cluster_labels,
        "distance_to_center":    own_center_distances,
        "text":            df_source["text"].values,
        "artist_id":        df_source["artist_id"],
        "is_artwork":      df_source["is_artwork"],
        "source_idx":            df_source["source_idx"].values
    })

    for c in range(n_clusters):
      results_df[f"dist_to_cluster_{c}"] = all_distances[:, c]

    if 'institution_id' in df_source.columns:
        results_df["institution_id"] = df_source["institution_id"].values

    if 'artist_name' in df_source.columns:
        results_df["artist_name"] = df_source["artist_name"].values

    return results_df

In [ ]:
ARTWORK_WEIGHT = 0.25  # weigh artwork titles and descriptions less in calculating centers

def get_all_clusters(fname, embeddings, lookups, n_clusters):
    weights = np.where(lookups["is_artwork"].values, ARTWORK_WEIGHT, 1.0)
    all_json_data = []

    for k in range(8, n_clusters):
        kmeans_model, labels = run_clustering_and_evaluate(embeddings, k, sample_weight=weights)

        distances = calculate_distances(embeddings, kmeans_model)

        keywords_dict = extract_cluster_keywords(lookups, labels, k, custom_stop_words)

        results_df = get_cluster_results_df(lookups, labels, distances, k)

        cluster_list = []
        for c in range(k):
            c_str = str(c)
            cluster_data = results_df[results_df['cluster'] == c].to_dict(orient='records')
            cluster_list.append({
                "key": c_str,
                "keywords": keywords_dict.get(c_str, []),
                "data": cluster_data
            })

        all_json_data.append({
            "n": k,
            "clusters": cluster_list
        })

    filename = fname + '.json'
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(all_json_data, f, indent=4, ensure_ascii=False)

    files.download(filename)

# Cluster by n

In [ ]:
get_all_clusters('inst_clusters_new', inst_embeddings_np, inst_lookup_df, 31)

================================================================================
FOR NUM CLUSTERS 8 --------------------
score:  -60.540863037109375
distance score:  0.3880484
silhouette score:  0.08432767
balance score:  0.5991836734693878

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 9 --------------------
score:  -59.26796340942383
distance score:  0.39884317
silhouette score:  0.0852088
balance score:  0.6067857142857143

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 10 --------------------
score:  -58.25251770019531
distance score:  0.40705132
silhouette score:  0.08177103
balance score:  0.6761904761904762

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 11 --------------------
score:  -57.157745361328125
distance score:  0.40969312
silhouette score:  0.08368416
balance score:  0.7388571428571429

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 12 --------------------
score:  -56.31703186035156
distance score:  0.4064394
silhouette score:  0.085596666
balance score:  0.6914285714285714

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 13 --------------------
score:  -55.58641052246094
distance score:  0.40059903
silhouette score:  0.08946937
balance score:  0.6580952380952381

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 14 --------------------
score:  -54.57769775390625
distance score:  0.4018244
silhouette score:  0.09227271
balance score:  0.6553846153846155

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 15 --------------------
score:  -53.623111724853516
distance score:  0.39728943
silhouette score:  0.09530696
balance score:  0.6285714285714286

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 16 --------------------
score:  -52.894744873046875
distance score:  0.39983046
silhouette score:  0.09236292
balance score:  0.6201904761904762

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 17 --------------------
score:  -51.947914123535156
distance score:  0.4015966
silhouette score:  0.09270828
balance score:  0.6282142857142856

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 18 --------------------
score:  -51.21438980102539
distance score:  0.40101227
silhouette score:  0.09893547
balance score:  0.6389915966386555

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 19 --------------------
score:  -50.605873107910156
distance score:  0.3969791
silhouette score:  0.10037201
balance score:  0.6215873015873016

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 20 --------------------
score:  -49.83995819091797
distance score:  0.40339327
silhouette score:  0.10611716
balance score:  0.6616541353383458

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 21 --------------------
score:  -49.61479568481445
distance score:  0.4069271
silhouette score:  0.097673304
balance score:  0.705

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 22 --------------------
score:  -48.97271728515625
distance score:  0.40690553
silhouette score:  0.09740361
balance score:  0.7197278911564625

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 23 --------------------
score:  -48.45881652832031
distance score:  0.40798718
silhouette score:  0.098416574
balance score:  0.7363636363636363

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 24 --------------------
score:  -47.6888313293457
distance score:  0.4052596
silhouette score:  0.099866636
balance score:  0.7277018633540373

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 25 --------------------
score:  -47.2359619140625
distance score:  0.40565532
silhouette score:  0.09776794
balance score:  0.7321428571428571

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 26 --------------------
score:  -46.62061309814453
distance score:  0.4047466
silhouette score:  0.0986901
balance score:  0.7302857142857143

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 27 --------------------
score:  -46.232276916503906
distance score:  0.40561268
silhouette score:  0.0997285
balance score:  0.738021978021978

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 28 --------------------
score:  -45.67634582519531
distance score:  0.4080427
silhouette score:  0.10782876
balance score:  0.7644444444444445

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 29 --------------------
score:  -44.988059997558594
distance score:  0.40556926
silhouette score:  0.11043165
balance score:  0.7678571428571428

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 30 --------------------
score:  -44.52094268798828
distance score:  0.40506694
silhouette score:  0.11323906
balance score:  0.7359605911330049

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

In [ ]:
get_all_clusters('ar_clusters_new', ar_embeddings_np, ar_lookup_df, 31)

================================================================================
FOR NUM CLUSTERS 8 --------------------
score:  -85.301025390625
distance score:  0.5168317
silhouette score:  0.03624398
balance score:  0.5765472312703583

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 9 --------------------
score:  -84.4991226196289
distance score:  0.51095635
silhouette score:  0.03477894
balance score:  0.5500814332247557

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 10 --------------------
score:  -82.60926818847656
distance score:  0.5056688
silhouette score:  0.04212205
balance score:  0.640246109301484

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 11 --------------------
score:  -82.22096252441406
distance score:  0.4980444
silhouette score:  0.038544837
balance score:  0.6087947882736156

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 12 --------------------
score:  -80.88300323486328
distance score:  0.4879342
silhouette score:  0.04351918
balance score:  0.6206692330470832

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 13 --------------------
score:  -80.4712905883789
distance score:  0.47609738
silhouette score:  0.049007628
balance score:  0.6095276872964168

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 14 --------------------
score:  -79.5194320678711
distance score:  0.4719526
silhouette score:  0.05767135
balance score:  0.6710097719869708

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 15 --------------------
score:  -78.98565673828125
distance score:  0.4681954
silhouette score:  0.059816398
balance score:  0.6610051186598418

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 16 --------------------
score:  -78.4238510131836
distance score:  0.46572128
silhouette score:  0.06175899
balance score:  0.6447339847991314

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 17 --------------------
score:  -77.94058227539062
distance score:  0.4641572
silhouette score:  0.06109137
balance score:  0.6304967426710097

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 18 --------------------
score:  -77.57524108886719
distance score:  0.46722236
silhouette score:  0.06343298
balance score:  0.6232994826595133

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 19 --------------------
score:  -77.2704849243164
distance score:  0.46683237
silhouette score:  0.06593027
balance score:  0.6227832066594281

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 20 --------------------
score:  -76.4195785522461
distance score:  0.45258182
silhouette score:  0.07242168
balance score:  0.6082633293331048

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 21 --------------------
score:  -76.84220886230469
distance score:  0.45904905
silhouette score:  0.04895773
balance score:  0.5509771986970683

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 22 --------------------
score:  -76.39683532714844
distance score:  0.45566037
silhouette score:  0.048171464
balance score:  0.5402512796649606

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 23 --------------------
score:  -76.21659851074219
distance score:  0.45564654
silhouette score:  0.047890555
balance score:  0.535978679301155

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 24 --------------------
score:  -75.1348876953125
distance score:  0.43161902
silhouette score:  0.061822657
balance score:  0.5376009063871974

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 25 --------------------
score:  -74.9015121459961
distance score:  0.4329998
silhouette score:  0.065368235
balance score:  0.5493349619978284

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 26 --------------------
score:  -74.160400390625
distance score:  0.42161897
silhouette score:  0.072343275
balance score:  0.5468403908794788

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 27 --------------------
score:  -73.81014251708984
distance score:  0.42208353
silhouette score:  0.07588453
balance score:  0.5580681533450262

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 28 --------------------
score:  -73.34879302978516
distance score:  0.42289945
silhouette score:  0.075263634
balance score:  0.5583303172879721

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 29 --------------------
score:  -72.86710357666016
distance score:  0.42201826
silhouette score:  0.075602666
balance score:  0.5499651000465333

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 30 --------------------
score:  -72.52748107910156
distance score:  0.42179602
silhouette score:  0.07571553
balance score:  0.5473435920476244

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(