In [1]:
!wget -q https://github.com/PSAM-5020-2026S-A/5020-utils/raw/main/src/data_utils.py

In [2]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
from sklearn.feature_extraction import text as sklearn_text

import numpy as np
import pandas as pd
import spacy
import torch.nn.functional as F
import torch
import umap
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import textwrap
from tqdm.notebook import tqdm
import re
import json

from google.colab import files
from data_utils import balance_score, distance_score, silhouette_score, display_silhouette_plots

# Load data and initialize model

In [3]:
# load data
artists_df = pd.read_csv('./artists.csv')
exhibitions_df = pd.read_csv('./exhibitions.csv')

artist_texts_df = pd.read_csv('./all_artist_texts.csv')
institution_texts_df = pd.read_csv('./all_institution_texts.csv')

artworks_df = pd.read_csv('./artworks.csv')
institutions_df = pd.read_csv('./institutions.csv')

# rename unnamed index
artist_texts_df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
institution_texts_df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)

institution_texts_df.head()

   id  institution                 text source_idx  artist  is_artwork
0   0            0  American, born 1975       IT01       1       False
1   1            0             American       IT02       1       False
2   2            0               female       IT03       1       False
3   3            0  American, born 1975       IT04       2       False
4   4            0             American       IT05       2       False

In [4]:
nlp = spacy.load("en_core_web_sm")
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)

if torch.cuda.is_available():
    print("using GPU")
    model.to('cuda')
else:
    print("using CPU")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/140 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

configuration_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- configuration_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- modeling_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/547M [00:00<?, ?B/s]

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

using GPU

# Text parsing helpers

*   semantic_chunk
*   get_word_weights
*   get_chunks_for_df

In [5]:
def get_word_weights(doc, vectorizer):
  doc_tfidf = vectorizer.transform([doc])
  feature_names = vectorizer.get_feature_names_out()

  df = pd.DataFrame(doc_tfidf[0].T.todense(),
                    index=feature_names,
                    columns=["tfidf"])

  ret = df.sort_values(by="tfidf", ascending=False)

  return ret.head(3).index.tolist()

In [6]:
def get_chunks_for_df(df, process_artworks, min_sentences=1):
  chunks_arr = []

  # Add tqdm to the iterrows loop for a progress bar
  for idx, row in tqdm(df.iterrows(), total=len(df), desc="Chunking texts"):
    if (row["text"] is not None):
      if (row["is_artwork"] and not process_artworks):
        # skip processing for artwork titles
        chunks_arr.append({
            "source_idx": row["source_idx"],
            "text": row["text"],
            "is_artwork": row["is_artwork"]
        })
      else:
        chunks = semantic_chunk(row["text"], 0.75, min_sentences)
        for chunk in chunks:
            chunks_arr.append({
                "source_idx": row["source_idx"],
                "text": chunk,
                "is_artwork": row["is_artwork"]
            })


  chunks_df = pd.DataFrame(chunks_arr)
  return chunks_df

In [1]:
def semantic_chunk(text, threshold=0.75, min_sentences=1, min_chars=100, max_sentences=3, max_chunk_chars=300):
    # replace double new lines with an explicit marker  to force a chunk split.
    processed_text = re.sub(r'\n\n+', '\n<PARAGRAPH_SPLIT_MARKER>\n', text)
    doc = nlp(processed_text)

    sentences_raw = [sent.text.strip() for sent in doc.sents if sent.text.strip()]

    if not sentences_raw:
        return []

    sentences_to_embed_flat = []
    original_idx_to_flat_indices = []

    current_flat_idx = 0
    for s_raw_text in sentences_raw:
        if '<PARAGRAPH_SPLIT_MARKER>' in s_raw_text:
            # if the sentence contains the marker, split it to extract actual text parts and discard the text
            parts = [p.strip() for p in s_raw_text.split('<PARAGRAPH_SPLIT_MARKER>') if p.strip()]
            if parts:
                original_idx_to_flat_indices.append((current_flat_idx, len(parts)))
                sentences_to_embed_flat.extend(parts)
                current_flat_idx += len(parts)
            else:
                original_idx_to_flat_indices.append((-1, 0))
        else:
            # add clean sentences to be embedded
            original_idx_to_flat_indices.append((current_flat_idx, 1))
            sentences_to_embed_flat.append(s_raw_text)
            current_flat_idx += 1

    if not sentences_to_embed_flat:
        return []

    embeddings_flat = model.encode(
        [f"search_document: {s}" for s in sentences_to_embed_flat],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    chunks = []
    current_chunk_sentences = []
    current_chunk_embeddings = []

    for i, sentence_raw_text in enumerate(sentences_raw):
        start_flat_idx, num_flat_sentences = original_idx_to_flat_indices[i]

        # for forced split points with no actual text
        if start_flat_idx == -1:
            if current_chunk_sentences:
                chunks.append(" ".join(current_chunk_sentences))
                current_chunk_sentences = []
                current_chunk_embeddings = []
            continue

        # iterate over extracted clean sentences
        for j in range(num_flat_sentences):
            sentence_to_process = sentences_to_embed_flat[start_flat_idx + j]
            embedding_to_process = embeddings_flat[start_flat_idx + j]

            prospective_chunk_len_sentences = len(current_chunk_sentences) + 1
            prospective_chunk_len_chars = sum(len(s) for s in current_chunk_sentences) + len(sentence_to_process)

            force_max_split = prospective_chunk_len_sentences > max_sentences or prospective_chunk_len_chars > max_chunk_chars

            semantically_different_split = False
            if current_chunk_sentences:
                current_char_count = sum(len(s) for s in current_chunk_sentences)
                meets_min_sentences_for_sem = len(current_chunk_sentences) >= min_sentences
                meets_min_chars_for_sem = current_char_count >= min_chars

                chunk_embedding = np.mean(current_chunk_embeddings, axis=0, keepdims=True)
                sim = cosine_similarity(chunk_embedding, embedding_to_process.reshape(1, -1))[0][0]
                semantically_different_split = sim < threshold and meets_min_sentences_for_sem and meets_min_chars_for_sem

            should_split = False
            if current_chunk_sentences and (force_max_split or semantically_different_split):
                should_split = True

            if should_split:
                chunks.append(" ".join(current_chunk_sentences))
                current_chunk_sentences = [sentence_to_process]
                current_chunk_embeddings = [embedding_to_process]
            else:
                current_chunk_sentences.append(sentence_to_process)
                current_chunk_embeddings.append(embedding_to_process)

    # finalize: merge trailing chunk backward if too short rather than discarding
    if current_chunk_sentences:
        leftover = " ".join(current_chunk_sentences)
        if len(leftover) < min_chars and chunks:
            chunks[-1] = chunks[-1] + " " + leftover
        else:
            chunks.append(leftover)

    # merge any short mid-stream chunks (e.g. from force splits) forward into the next
    result = []
    for chunk in chunks:
        if result and len(result[-1]) < min_chars:
            result[-1] = result[-1] + " " + chunk
        else:
            result.append(chunk)

    return [c for c in result if len(c) >= min_chars]

# Prep data

In [8]:
# get all exhibition text
exhibitions_df['full_text'] = exhibitions_df['name'].fillna('') + ". " + exhibitions_df['description'].fillna('')

In [9]:
# chunk artist texts
ar_texts = get_chunks_for_df(artist_texts_df, False, 2)

Chunking texts:   0%|          | 0/584 [00:00<?, ?it/s]

In [10]:
print(len(ar_texts))
ar_texts.head()

7576

  source_idx                                               text  is_artwork
0       AT01  That’s a great question, but also a rabbit hol...       False
1       AT01  I wanted to directly challenge previous assert...       False
2       AT01  I think of my work as an organism that fluctua...       False
3       AT01  I’ve always been interested in the shared real...       False
4       AT01  In previous works, I mined the generic for fou...       False

In [11]:
# chunk inst texts
inst_texts = get_chunks_for_df(institution_texts_df, True, 1)

Chunking texts:   0%|          | 0/338 [00:00<?, ?it/s]

In [12]:
print(len(inst_texts))
inst_texts.head()

846

  source_idx                 text  is_artwork
0       IT01  American, born 1975       False
1       IT02             American       False
2       IT03               female       False
3       IT04  American, born 1975       False
4       IT05             American       False

# Labeling - stop words

In [49]:
new_stop_words = ["biennale", "biennial", "museum", "exhibition", "baratta", "italian", "year", "s", "art", "artist", "th", "arsenale", "tam", "t", "identity"]
custom_stop_words = list(sklearn_text.ENGLISH_STOP_WORDS.union(new_stop_words))

In [14]:
# add all the artist first and last names to the stop words list
for idx, row in artists_df.iterrows():
    # split by first and last name
    names = re.split(r'[- ]', row["name"])

    for name in names:
      custom_stop_words.append(name.lower())

# add all locations
for idx, row in exhibitions_df.iterrows():
  locations = re.split(r'[, ]', row["location"])

  for location in locations:
    custom_stop_words.append(location.lower())

In [15]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text.lower())

# Identity relevance queries

In [18]:
query_words = [
    # original
    "identity", "persona", "race", "ethnicity", "culture",
    "self", "category", "belonging", "community",
    "ancestry", "generation", "experience", "in-between",

    # mixed race
    "mixed", "multiracial", "biracial", "half", "hyphenated",
    "passing", "blood", "skin", "contradict"

    # diaspora
    "diaspora", "diasporic", "transnational", "immigrant", "migration",
    "displacement", "exile", "homeland", "motherland", "origin",

    # in betweenness
    "liminal", "borderlands", "threshold", "assimilation", "integration",

    # heritage
    "heritage", "roots", "memory", "nostalgia", "home", "tradition",
    "language", "birth", "death", "born", "nationality", "died"

    # visibility
    "otherness", "outsider", "minority", "visibility", "authenticity",
    "representation", "erasure", "recognition", "voice", "truth",
    "invisible", "seen", "silence", "absence"
]

In [53]:
# self relevance query to get first-person testimony about the artist's own experience rather than framing others
self_query = (
    "search_query: speaking in my own voice about who I am — "
    "my mixed heritage, my family's immigration story, growing up caught between cultures, "
    "and how my racial and ethnic identity lives in my body and my life"
)

# keyword sorting query — emphasizes specific descriptive terms over generic labels
keyword_sort_query = (
    "search_query: mixed race biracial multiracial diaspora ancestry homeland "
    "displacement immigration heritage roots belonging between cultures hyphenated "
    "passing invisible representation erasure"
)

In [54]:
identity_query = "search_query: " + " ".join(query_words)
identity_query_embedding = model.encode(identity_query, convert_to_numpy=True, normalize_embeddings=True)

In [55]:
# for sorting keyword labels — separate from text filtering query
keyword_sort_query_embedding = model.encode(keyword_sort_query, convert_to_numpy=True, normalize_embeddings=True)

# Exhibition labels

In [16]:
all_corpus = exhibitions_df['full_text'].tolist()

vectorizer = TfidfVectorizer(preprocessor=remove_numbers, stop_words=custom_stop_words)

tfidf_matrix = vectorizer.fit_transform(all_corpus)

In [17]:
# get word weights for each row in exhibitions
exhibitions_df["labels"] = exhibitions_df.apply(lambda row: get_word_weights(row['full_text'], vectorizer), axis=1)
exhibitions_df["labels"]

0                 [hapa, ancestry, asian]
1                [mixed, asian, american]
2               [citizen, universe, life]
3                 [orient, dis, diaspora]
4             [legacies, asian, american]
5                  [east, asian, chinese]
6       [countries, international, world]
7     [ideologies, global, authoritarian]
8              [korean, english, pacific]
9               [hard, american, america]
10      [portraiture, asian, smithsonian]
11         [ascendancy, agency, personal]
12             [american, asian, chinese]
13           [decade, studio, frameworks]
Name: labels, dtype: object

In [56]:
# sort exhibition labels by identity relevance
def sort_labels_by_identity(labels):
    kw_embeddings = model.encode(
        ["search_document: " + kw for kw in labels],
        convert_to_numpy=True, normalize_embeddings=True
    )
    sims = cosine_similarity([keyword_sort_query_embedding], kw_embeddings)[0]
    return [kw for _, kw in sorted(zip(sims, labels), reverse=True)]

exhibitions_df["labels"] = exhibitions_df["labels"].apply(sort_labels_by_identity)
exhibitions_df["labels"]

0                 [ancestry, hapa, asian]
1                [mixed, asian, american]
2               [citizen, life, universe]
3                 [diaspora, orient, dis]
4             [legacies, asian, american]
5                  [chinese, asian, east]
6       [countries, international, world]
7     [ideologies, global, authoritarian]
8              [korean, pacific, english]
9               [america, american, hard]
10      [asian, smithsonian, portraiture]
11         [ascendancy, personal, agency]
12             [chinese, asian, american]
13           [studio, decade, frameworks]
Name: labels, dtype: object

In [23]:
# download w labels
exhibitions_df.to_csv('exhibitions_with_labels.csv', index=False)

files.download('exhibitions_with_labels.csv')

# Filter for identity-specific texts

For artists

In [63]:
# density of first person words to filter for speaking about self
def _fp_density(text):
    words = re.findall(r'\b\w+\b', text.lower())
    fp = sum(1 for w in words if w in {'i', 'me', 'my', 'mine', 'myself'})
    return fp / max(len(words), 1)

In [64]:
chunk_embeddings_for_filter = model.encode(
    ["search_document: " + t for t in ar_texts["text"]],
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/20 [00:00<?, ?it/s]

In [65]:
# get identity relevance first
ar_texts["identity_relevance"] = cosine_similarity([identity_query_embedding], chunk_embeddings_for_filter)[0]

# get self relevance
self_query_embedding = model.encode(self_query, convert_to_numpy=True, normalize_embeddings=True)
ar_texts["self_relevance"] = cosine_similarity([self_query_embedding], chunk_embeddings_for_filter)[0]

# first person density words to tiebreak in some cases
ar_texts["fp_density"] = ar_texts["text"].apply(_fp_density)
fp_norm_cap = 0.15
ar_texts["fp_density_norm"] = (ar_texts["fp_density"] / fp_norm_cap).clip(upper=1.0)

# weigh priority
ar_texts["priority_score"] = (
    ar_texts["identity_relevance"] * 0.35
    + ar_texts["self_relevance"]   * 0.55
    + ar_texts["fp_density_norm"]  * 0.10
)

# per-artist floor + ceiling using priority score
THRESHOLD = 0.6   # for identity_relevance to filter to topic
MIN_QUOTES = 3
MAX_QUOTES = 12

source_to_artist = artist_texts_df.set_index('source_idx')['artist'].to_dict()
ar_texts['artist_id'] = ar_texts['source_idx'].map(source_to_artist)

def filter_artist_quotes(group):
    above = group[group['identity_relevance'] >= THRESHOLD]
    if len(above) >= MIN_QUOTES:
        return above.nlargest(MAX_QUOTES, 'priority_score')
    else:
        return group.nlargest(MIN_QUOTES, 'priority_score')

non_artwork = ar_texts[ar_texts['is_artwork'] == False]
artworks    = ar_texts[ar_texts['is_artwork'] == True]

filtered_text = non_artwork.groupby('artist_id', group_keys=False).apply(filter_artist_quotes)
filtered_ar_texts = pd.concat([filtered_text, artworks]).reset_index(drop=True)

print(f"Rows remaining: {len(filtered_ar_texts)}")
print(f"\nArtist text chunks per artist:\n{filtered_text.groupby('artist_id').size().sort_values()}")

Rows remaining: 613

Artist text chunks per artist:
artist_id
0      3
1      3
5      3
8      3
10     3
12     3
19     3
17     3
27     3
21     3
28     3
29     4
6      4
25     4
2      4
13     5
26     6
16     8
14    10
24    11
7     11
3     12
9     12
4     12
15    12
11    12
20    12
18    12
23    12
22    12
dtype: int64

/tmp/ipykernel_540/771909683.py:38: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  filtered_text = non_artwork.groupby('artist_id', group_keys=False).apply(filter_artist_quotes)

In [66]:
texts_only = filtered_ar_texts[filtered_ar_texts["is_artwork"] == False]
texts_only.to_csv('ar_texts_filtered.csv', index=False)
files.download('ar_texts_filtered.csv')

For institutions

In [57]:
inst_chunk_embeddings_for_filter = model.encode(
      ["search_document: " + t for t in inst_texts["text"]],
      convert_to_numpy=True,
      normalize_embeddings=True,
      show_progress_bar=True
  )

Batches:   0%|          | 0/11 [00:00<?, ?it/s]

In [58]:
# reuses identity_query_embedding already computed in the artist filter above
inst_texts["identity_relevance"] = cosine_similarity(
    [identity_query_embedding], inst_chunk_embeddings_for_filter
)[0]

In [59]:
INST_ARTWORK_THRESHOLD = 0.3
INST_NON_ARTWORK_THRESHOLD = 0.12
INST_MIN_TEXTS = 3
INST_MAX_TEXTS = 20
source_to_artist_inst = institution_texts_df.set_index('source_idx')['artist'].to_dict()
inst_texts['artist_id'] = inst_texts['source_idx'].map(source_to_artist_inst)

In [60]:
def filter_inst_texts(group):
    non_art = group[group['is_artwork'] == False]
    art     = group[group['is_artwork'] == True]

    # apply loose threshold to non-artwork; pad to floor if nothing passes
    non_art_above = non_art[non_art['identity_relevance'] >= INST_NON_ARTWORK_THRESHOLD]
    if len(non_art_above) == 0:
        non_art_above = non_art.nlargest(1, 'identity_relevance')

    # apply modest threshold to artwork; pad to floor if not enough pass
    art_above = art[art['identity_relevance'] >= INST_ARTWORK_THRESHOLD]
    if len(art_above) < INST_MIN_TEXTS and len(art) > 0:
        n_needed = INST_MIN_TEXTS - len(art_above)
        art_pad  = art[art['identity_relevance'] < INST_ARTWORK_THRESHOLD].nlargest(n_needed, 'identity_relevance')
        kept_art = pd.concat([art_above, art_pad])
    else:
        kept_art = art_above

    # hard cap: non-artwork gets priority slots, artwork fills the rest
    non_art_capped = non_art_above.nlargest(INST_MAX_TEXTS, 'identity_relevance')
    n_art_slots    = max(0, INST_MAX_TEXTS - len(non_art_capped))
    art_capped     = kept_art.nlargest(n_art_slots, 'identity_relevance')
    combined       = pd.concat([non_art_capped, art_capped])

    return combined

In [61]:
filtered_inst_texts = (
    inst_texts
    .groupby('artist_id', group_keys=False)
    .apply(filter_inst_texts, include_groups=False)
    .reset_index(drop=True)
)

filtered_inst_texts['artist_id'] = filtered_inst_texts['source_idx'].map(source_to_artist_inst)

# inst_texts = filtered_inst_texts   # downstream cells (cell 37 + 43) pick this up automatically
print(f"before: {len(inst_texts)}")
print(f"After filter: {len(filtered_inst_texts)} rows")
print(f"\nInst chunks per artist:\n{filtered_inst_texts.groupby('artist_id').size().sort_values()}")

before: 349
After filter: 349 rows

Inst chunks per artist:
artist_id
24     2
20     2
18     2
17     2
1      3
3      3
7      3
26     4
23     5
2      5
28     7
19     7
4      9
11     9
14     9
15    10
16    15
13    15
6     17
8     20
0     20
5     20
9     20
10    20
12    20
21    20
22    20
25    20
27    20
29    20
dtype: int64

In [62]:
inst_texts = filtered_inst_texts

# Embed all texts

For artists

In [34]:
ar_texts = filtered_ar_texts

In [35]:
ar_texts_arr = ["clustering: " + t for t in ar_texts["text"].tolist()]

# embed
ar_embeddings = model.encode(
    ar_texts_arr,
    batch_size=64,
    convert_to_tensor=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

ar_embeddings_np = ar_embeddings.cpu().numpy()

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

For institutions

In [36]:
inst_texts_arr = ["clustering: " + t for t in inst_texts["text"].tolist()]

# embed
inst_embeddings = model.encode(
    inst_texts_arr,
    batch_size=64,
    convert_to_tensor=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

inst_embeddings_np = inst_embeddings.cpu().numpy()

Batches:   0%|          | 0/6 [00:00<?, ?it/s]

# Build lookups

In [37]:
artist_texts_source_idx_map = artist_texts_df.set_index('source_idx')
institution_texts_source_idx_map = institution_texts_df.set_index('source_idx')

artworks_source_idx_map = artworks_df.set_index('id')

In [38]:
def map_metadata(row, mode):
    artist_id = np.nan
    institution_id = np.nan

    if mode == 'artist':
      source_idx_map = artist_texts_source_idx_map
    else:
      source_idx_map = institution_texts_source_idx_map

    if row['is_artwork']:
        artwork_row = artworks_source_idx_map.loc[row['source_idx']]
        artist_id = artwork_row['artist']
        institution_id = artwork_row['institution']
    else:
        artist_id = source_idx_map.loc[row['source_idx'], 'artist']
        if mode != 'artist':
          institution_id = source_idx_map.loc[row['source_idx'], 'institution']

    return pd.Series({'artist_id': artist_id, 'institution_id': institution_id})

In [39]:
artist_id_to_name = artists_df.set_index("id")["name"].to_dict()
inst_id_to_name = institutions_df.set_index("id")["name"].to_dict()

ar_lookup_df = ar_texts[["text", "source_idx", "is_artwork"]].copy()

ar_lookup_df[['artist_id', 'institution_id']] = ar_lookup_df.apply(lambda x: map_metadata(x, 'artist'), axis=1)

ar_lookup_df['artist_id'] = ar_lookup_df['artist_id'].astype(pd.Int64Dtype())
ar_lookup_df['institution_id'] = ar_lookup_df['institution_id'].astype(pd.Int64Dtype())

# for testing, map to names to see accuracy
ar_lookup_df['artist_name'] = ar_lookup_df['artist_id'].map(artist_id_to_name)
ar_lookup_df['institution_name'] = ar_lookup_df['institution_id'].map(inst_id_to_name)

ar_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"So, I’m still a struggling artist—at least in ...",AT53,False,0,<NA>,Isamu Noguchi,NaN
1,So I don’t have much faith in myself as a kind...,AT54,False,0,<NA>,Isamu Noguchi,NaN
2,It’s what keeps me going.,AT53,False,0,<NA>,Isamu Noguchi,NaN
3,I think one of the things that’s interesting f...,AT02,False,1,<NA>,Amanda Ross-Ho,NaN
4,Navigating this stuff allows me to investigate...,AT01,False,1,<NA>,Amanda Ross-Ho,NaN
...,...,...,...,...,...,...,...
608,Belly Painting: Prussian Blue,W405,True,12,7,Byron Kim,National Gallery of Art
609,Untitled,W406,True,29,7,Hung Liu,National Gallery of Art
610,Post-Age,W407,True,29,7,Hung Liu,National Gallery of Art
611,Seoul Home – Inverted,W408,True,6,7,Do Ho Suh,National Gallery of Art
612,Prison Bunk Beds,W409,True,10,7,Martin Wong,National Gallery of Art

In [40]:
inst_lookup_df = inst_texts[["text", "source_idx", "is_artwork"]].copy()

inst_lookup_df[['artist_id', 'institution_id']] = inst_lookup_df.apply(lambda x: map_metadata(x, 'institution'), axis=1)

inst_lookup_df['artist_id'] = inst_lookup_df['artist_id'].astype(pd.Int64Dtype())
# inst_lookup_df['institution_id'] = inst_lookup_df['institution_id'].astype(pd.Int64Dtype())

# add names for testing
inst_lookup_df['artist_name'] = inst_lookup_df['artist_id'].map(artist_id_to_name)
inst_lookup_df['institution_name'] = inst_lookup_df['institution_id'].map(inst_id_to_name)

inst_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,His encounter with the organic shapes (or “bio...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
1,"Back in New York, Noguchi created a series of ...",IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
2,Drawing inspiration from ancient forms--from J...,IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
3,He also created portrait busts and dance and t...,IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
4,Isamu Noguchi regarded his sculptures not as r...,IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
...,...,...,...,...,...,...,...
344,Here she updates her blue and gray peasant att...,W274,True,29,3,Hung Liu,Metropolitan Museum of Art
345,The juxtaposition of familiar shapes suggests ...,W406,True,29,7,Hung Liu,National Gallery of Art
346,Faded pink oval portrait of a young woman surr...,W280,True,29,0,Hung Liu,Museum of Modern Art
347,"In an interview, Liu described the original ph...",W274,True,29,3,Hung Liu,Metropolitan Museum of Art
348,Portrait of a young woman in an oval frame wit...,W281,True,29,0,Hung Liu,Museum of Modern Art

In [41]:
inst_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,His encounter with the organic shapes (or “bio...,IT17,False,0,1,Isamu Noguchi,Whitney Museum of American Art
1,"Back in New York, Noguchi created a series of ...",IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
2,Drawing inspiration from ancient forms--from J...,IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
3,He also created portrait busts and dance and t...,IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
4,Isamu Noguchi regarded his sculptures not as r...,IT24,False,0,6,Isamu Noguchi,J. Paul Getty Center
...,...,...,...,...,...,...,...
344,Here she updates her blue and gray peasant att...,W274,True,29,3,Hung Liu,Metropolitan Museum of Art
345,The juxtaposition of familiar shapes suggests ...,W406,True,29,7,Hung Liu,National Gallery of Art
346,Faded pink oval portrait of a young woman surr...,W280,True,29,0,Hung Liu,Museum of Modern Art
347,"In an interview, Liu described the original ph...",W274,True,29,3,Hung Liu,Metropolitan Museum of Art
348,Portrait of a young woman in an oval frame wit...,W281,True,29,0,Hung Liu,Museum of Modern Art

# Helpers to cluster for n

In [67]:
def run_clustering_and_evaluate(embeddings, n_clusters, sample_weight=None):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init="auto")
    cluster_labels = kmeans.fit_predict(embeddings, sample_weight=sample_weight)

    sc = kmeans.score(embeddings, sample_weight=sample_weight)
    distance_sc = distance_score(embeddings, cluster_labels)
    silhouette_sc = silhouette_score(embeddings, cluster_labels)
    balance_sc = balance_score(cluster_labels)

    print(f"\n{'='*80}")
    print(f"FOR NUM CLUSTERS {n_clusters} --------------------")
    print("score: ", sc)
    print("distance score: ", distance_sc)
    print("silhouette score: ", silhouette_sc)
    print("balance score: ", balance_sc)

    return kmeans, cluster_labels

In [68]:
def calculate_distances(embeddings_np, kmeans):
    centers = kmeans.cluster_centers_
    all_distances = euclidean_distances(embeddings_np, centers)

    return all_distances

In [69]:
def extract_cluster_keywords(df_source, cluster_labels, n_clusters, stop_words):
      temp_df = df_source.copy()
      temp_df["cluster"] = cluster_labels
      cluster_texts = []
      for c in range(n_clusters):
          mask = temp_df["cluster"] == c
          combined = " ".join(temp_df.loc[mask, "text"].tolist())
          cluster_texts.append(combined)
      vectorizer = TfidfVectorizer(preprocessor=remove_numbers, stop_words=stop_words, token_pattern=r'\b\w*[a-zA-Z]\w*\b', max_features=1000, ngram_range=(1,1))
      tfidf_matrix = vectorizer.fit_transform(cluster_texts)
      feature_names = vectorizer.get_feature_names_out()
      top_n = 5
      cluster_keywords = {}
      for c in range(n_clusters):
          top_indices = np.argsort(tfidf_matrix[c].toarray()[0])[::-1][:top_n]
          keywords = [feature_names[i] for i in top_indices]
          kw_embeddings = model.encode(
              ["search_document: " + kw for kw in keywords],
              convert_to_numpy=True, normalize_embeddings=True
          )
          kw_sims = cosine_similarity([keyword_sort_query_embedding], kw_embeddings)[0]
          keywords = [kw for _, kw in sorted(zip(kw_sims, keywords), reverse=True)]
          cluster_keywords[str(c)] = keywords
      return cluster_keywords

In [70]:
def get_cluster_results_df(df_source, cluster_labels, all_distances, n_clusters):
    own_center_distances = all_distances[range(len(cluster_labels)), cluster_labels]

    masked = all_distances.copy()
    masked[range(len(cluster_labels)), cluster_labels] = np.inf
    closest_other_cluster = np.argmin(masked, axis=1)
    closest_other_cluster_distance = masked[range(len(cluster_labels)), closest_other_cluster]

    results_df = pd.DataFrame({
        "point":                 range(len(cluster_labels)),
        "cluster":               cluster_labels,
        "distance_to_center":    own_center_distances,
        "text":            df_source["text"].values,
        "artist_id":        df_source["artist_id"],
        "is_artwork":      df_source["is_artwork"],
        "source_idx":            df_source["source_idx"].values
    })

    for c in range(n_clusters):
      results_df[f"dist_to_cluster_{c}"] = all_distances[:, c]

    if 'institution_id' in df_source.columns:
        results_df["institution_id"] = df_source["institution_id"].values

    if 'artist_name' in df_source.columns:
        results_df["artist_name"] = df_source["artist_name"].values

    return results_df

In [71]:
ARTWORK_WEIGHT = 0.25  # weigh artwork titles and descriptions less in calculating centers

def get_all_clusters(fname, embeddings, lookups, n_clusters):
    weights = np.where(lookups["is_artwork"].values, ARTWORK_WEIGHT, 1.0)
    all_json_data = []

    for k in range(8, n_clusters):
        kmeans_model, labels = run_clustering_and_evaluate(embeddings, k, sample_weight=weights)

        distances = calculate_distances(embeddings, kmeans_model)

        keywords_dict = extract_cluster_keywords(lookups, labels, k, custom_stop_words)

        results_df = get_cluster_results_df(lookups, labels, distances, k)

        cluster_list = []
        for c in range(k):
            c_str = str(c)
            cluster_data = results_df[results_df['cluster'] == c].to_dict(orient='records')
            cluster_list.append({
                "key": c_str,
                "keywords": keywords_dict.get(c_str, []),
                "data": cluster_data
            })

        all_json_data.append({
            "n": k,
            "clusters": cluster_list
        })

    filename = fname + '.json'
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(all_json_data, f, indent=4, ensure_ascii=False)

    files.download(filename)

# Cluster by n

In [74]:
get_all_clusters('inst_clusters_new', inst_embeddings_np, inst_lookup_df, 31)

================================================================================
FOR NUM CLUSTERS 8 --------------------
score:  -72.65933227539062
distance score:  0.45398933
silhouette score:  0.05785995
balance score:  0.716741711011052

================================================================================
FOR NUM CLUSTERS 9 --------------------
score:  -71.62151336669922
distance score:  0.4526051
silhouette score:  0.060189787
balance score:  0.7288681948424068

================================================================================
FOR NUM CLUSTERS 10 --------------------
score:  -70.7738265991211
distance score:  0.44907174
silhouette score:  0.059890583
balance score:  0.6774912448264884

================================================================================
FOR NUM CLUSTERS 11 --------------------
score:  -69.38959503173828
distance score:  0.43659547
silhouette score:  0.06417674
balance score:  0.681375358166189

================================================================================
FOR NUM CLUSTERS 12 --------------------
score:  -68.36322021484375
distance score:  0.44471025
silhouette score:  0.06770888
balance score:  0.7040896066684033

================================================================================
FOR NUM CLUSTERS 13 --------------------
score:  -67.06083679199219
distance score:  0.4429469
silhouette score:  0.07268625
balance score:  0.6685768863419294

================================================================================
FOR NUM CLUSTERS 14 --------------------
score:  -66.22647857666016
distance score:  0.44662008
silhouette score:  0.0727358
balance score:  0.7121445889354199

================================================================================
FOR NUM CLUSTERS 15 --------------------
score:  -65.0968017578125
distance score:  0.44805717
silhouette score:  0.0755955
balance score:  0.7400736799017602

================================================================================
FOR NUM CLUSTERS 16 --------------------
score:  -64.08021545410156
distance score:  0.44703013
silhouette score:  0.07791825
balance score:  0.7667621776504299

================================================================================
FOR NUM CLUSTERS 17 --------------------
score:  -63.729122161865234
distance score:  0.44402245
silhouette score:  0.07593923
balance score:  0.7478510028653296

================================================================================
FOR NUM CLUSTERS 18 --------------------
score:  -62.97344970703125
distance score:  0.44032884
silhouette score:  0.07652245
balance score:  0.7583010281476488

================================================================================
FOR NUM CLUSTERS 19 --------------------
score:  -61.82862854003906
distance score:  0.4345579
silhouette score:  0.078560136
balance score:  0.7416427889207259

================================================================================
FOR NUM CLUSTERS 20 --------------------
score:  -61.31909942626953
distance score:  0.43482202
silhouette score:  0.08062889
balance score:  0.7470969687829889

================================================================================
FOR NUM CLUSTERS 21 --------------------
score:  -59.87965774536133
distance score:  0.42765698
silhouette score:  0.085822925
balance score:  0.763323782234957

================================================================================
FOR NUM CLUSTERS 22 --------------------
score:  -59.171451568603516
distance score:  0.42833987
silhouette score:  0.08877551
balance score:  0.7866011734206577

================================================================================
FOR NUM CLUSTERS 23 --------------------
score:  -58.64792251586914
distance score:  0.42984578
silhouette score:  0.08896741
balance score:  0.8099765563948945

================================================================================
FOR NUM CLUSTERS 24 --------------------
score:  -57.59524917602539
distance score:  0.4255776
silhouette score:  0.09268546
balance score:  0.7949420705120219

================================================================================
FOR NUM CLUSTERS 25 --------------------
score:  -56.98890686035156
distance score:  0.4240557
silhouette score:  0.09376238
balance score:  0.7929799426934097

================================================================================
FOR NUM CLUSTERS 26 --------------------
score:  -56.58922576904297
distance score:  0.42108777
silhouette score:  0.09121809
balance score:  0.7789111747851003

================================================================================
FOR NUM CLUSTERS 27 --------------------
score:  -55.75312805175781
distance score:  0.41753733
silhouette score:  0.09381152
balance score:  0.7714348688560723

================================================================================
FOR NUM CLUSTERS 28 --------------------
score:  -55.32569122314453
distance score:  0.41542068
silhouette score:  0.09439415
balance score:  0.7639817467897697

================================================================================
FOR NUM CLUSTERS 29 --------------------
score:  -54.806861877441406
distance score:  0.41570032
silhouette score:  0.096034415
balance score:  0.7871469504707327

================================================================================
FOR NUM CLUSTERS 30 --------------------
score:  -54.60810852050781
distance score:  0.40713045
silhouette score:  0.092243895
balance score:  0.7702796166386721

In [73]:
get_all_clusters('ar_clusters', ar_embeddings_np, ar_lookup_df, 31)

================================================================================
FOR NUM CLUSTERS 8 --------------------
score:  -83.85517120361328
distance score:  0.5068961
silhouette score:  0.041565496
balance score:  0.6947098578419948

================================================================================
FOR NUM CLUSTERS 9 --------------------
score:  -83.39514923095703
distance score:  0.50136065
silhouette score:  0.0360103
balance score:  0.659257748776509

================================================================================
FOR NUM CLUSTERS 10 --------------------
score:  -82.49242401123047
distance score:  0.49498254
silhouette score:  0.04328825
balance score:  0.6802610114192496

================================================================================
FOR NUM CLUSTERS 11 --------------------
score:  -81.67359924316406
distance score:  0.493515
silhouette score:  0.04399282
balance score:  0.670636215334421

================================================================================
FOR NUM CLUSTERS 12 --------------------
score:  -80.39204406738281
distance score:  0.47169378
silhouette score:  0.057901394
balance score:  0.6887142221563103

================================================================================
FOR NUM CLUSTERS 13 --------------------
score:  -79.8199234008789
distance score:  0.47083738
silhouette score:  0.06262797
balance score:  0.6874660141381186

================================================================================
FOR NUM CLUSTERS 14 --------------------
score:  -79.33493041992188
distance score:  0.47168583
silhouette score:  0.06037099
balance score:  0.6861588656042164

================================================================================
FOR NUM CLUSTERS 15 --------------------
score:  -78.4700927734375
distance score:  0.45652348
silhouette score:  0.06773059
balance score:  0.6742018177580984

================================================================================
FOR NUM CLUSTERS 16 --------------------
score:  -78.17157745361328
distance score:  0.45660308
silhouette score:  0.06652203
balance score:  0.6611201740076129

================================================================================
FOR NUM CLUSTERS 17 --------------------
score:  -77.65876007080078
distance score:  0.4554155
silhouette score:  0.06575132
balance score:  0.6468189233278956

================================================================================
FOR NUM CLUSTERS 18 --------------------
score:  -77.00733947753906
distance score:  0.4549897
silhouette score:  0.07040118
balance score:  0.6428365799827273

================================================================================
FOR NUM CLUSTERS 19 --------------------
score:  -76.5564193725586
distance score:  0.44718397
silhouette score:  0.07006
balance score:  0.6315932572050027

================================================================================
FOR NUM CLUSTERS 20 --------------------
score:  -76.25836181640625
distance score:  0.45149907
silhouette score:  0.07285651
balance score:  0.6535588563578604

================================================================================
FOR NUM CLUSTERS 21 --------------------
score:  -75.38642883300781
distance score:  0.43535388
silhouette score:  0.0768663
balance score:  0.5665579119086461

================================================================================
FOR NUM CLUSTERS 22 --------------------
score:  -74.75214385986328
distance score:  0.41712725
silhouette score:  0.08465258
balance score:  0.5544939019653539

================================================================================
FOR NUM CLUSTERS 23 --------------------
score:  -74.26470947265625
distance score:  0.39926064
silhouette score:  0.08483862
balance score:  0.5450837905976569

================================================================================
FOR NUM CLUSTERS 24 --------------------
score:  -73.67529296875
distance score:  0.39700875
silhouette score:  0.084673546
balance score:  0.546705440102135

================================================================================
FOR NUM CLUSTERS 25 --------------------
score:  -73.29788970947266
distance score:  0.39828777
silhouette score:  0.08340836
balance score:  0.5439097335508428

================================================================================
FOR NUM CLUSTERS 26 --------------------
score:  -72.88978576660156
distance score:  0.39831746
silhouette score:  0.08265791
balance score:  0.534942903752039

================================================================================
FOR NUM CLUSTERS 27 --------------------
score:  -72.41032409667969
distance score:  0.3986293
silhouette score:  0.08385562
balance score:  0.5282344083322876

================================================================================
FOR NUM CLUSTERS 28 --------------------
score:  -71.88956451416016
distance score:  0.40105996
silhouette score:  0.08766016
balance score:  0.5573681348558999

================================================================================
FOR NUM CLUSTERS 29 --------------------
score:  -71.48790740966797
distance score:  0.40642428
silhouette score:  0.09059132
balance score:  0.5843043579585179

================================================================================
FOR NUM CLUSTERS 30 --------------------
score:  -70.9577407836914
distance score:  0.40772757
silhouette score:  0.0909753
balance score:  0.5764752207909096

## Combine artist-specific texts from both sources

In [ ]:
combined_artist_data = []

ar_data_for_combine = ar_lookup_df.copy()
ar_data_for_combine = ar_data_for_combine[['artist_id', 'institution_id', 'is_artwork', 'source_idx', 'text']]

inst_data_for_combine = inst_lookup_df.copy()
inst_data_for_combine = inst_data_for_combine[['artist_id', 'institution_id', 'is_artwork', 'source_idx', 'text']]

all_artist_points_df = pd.concat([ar_data_for_combine, inst_data_for_combine], ignore_index=True)

display(all_artist_points_df.head())

all_artist_points_df.to_csv('all_artist_combined_texts.csv')
files.download('all_artist_combined_texts.csv')

,artist_id,institution_id,is_artwork,source_idx,text
0,0,<NA>,False,AT53,"So, I’m still a struggling artist—at least in ..."
1,0,<NA>,False,AT54,So I don’t have much faith in myself as a kind...
2,0,<NA>,False,AT53,It’s what keeps me going.
3,1,<NA>,False,AT01,The important thing is that I wasn’t intereste...
4,1,<NA>,False,AT04,My practice originates in the act of negotiati...