In [37]:
!wget -q https://github.com/PSAM-5020-2026S-A/5020-utils/raw/main/src/data_utils.py

In [38]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
from sklearn.feature_extraction import text as sklearn_text

import numpy as np
import pandas as pd
import spacy
import torch.nn.functional as F
import torch
import umap
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import textwrap
from tqdm.notebook import tqdm
import re
import json

from google.colab import files
from data_utils import balance_score, distance_score, silhouette_score, display_silhouette_plots

# Load data and initialize model

In [39]:
# load data
artists_df = pd.read_csv('./artists.csv')
exhibitions_df = pd.read_csv('./exhibitions.csv')

artist_texts_df = pd.read_csv('./all_artist_texts.csv')
institution_texts_df = pd.read_csv('./all_institution_texts.csv')

artworks_df = pd.read_csv('./artworks.csv')
institutions_df = pd.read_csv('./institutions.csv')

# rename unnamed index
artist_texts_df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
institution_texts_df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)

institution_texts_df.head()

   id  institution                 text source_idx  artist  is_artwork
0   0            0  American, born 1975       IT01       1       False
1   1            0             American       IT02       1       False
2   2            0               female       IT03       1       False
3   3            0  American, born 1975       IT04       2       False
4   4            0             American       IT05       2       False

In [40]:
nlp = spacy.load("en_core_web_sm")
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)

if torch.cuda.is_available():
    print("using GPU")
    model.to('cuda')
else:
    print("using CPU")

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

using GPU

# Text parsing helpers

*   semantic_chunk
*   get_word_weights
*   get_chunks_for_df

In [41]:
# based on semantic similarity between sentences
def semantic_chunk(text, threshold=0.75, min_sentences=1, min_chars=100, max_sentences=3, max_chunk_chars=300):
    # replace unended double new lines for splitting equally
    processed_text = re.sub(r'\n\n+', '. ', text)
    doc = nlp(processed_text)
    sentences = [sent.text.strip() for sent in doc.sents if sent.text.strip()]

    if len(sentences) <= min_sentences:
        return [text]

    # embed sentences to compare similarity
    embeddings = model.encode(
        [f"search_document: {s}" for s in sentences],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    chunks = []
    current_chunk = [sentences[0]]

    for i in range(1, len(sentences)):
        # compare current sentence to mean of the current chunk
        chunk_embedding = embeddings[i - len(current_chunk):i].mean(axis=0, keepdims=True)
        sim = cosine_similarity(chunk_embedding, embeddings[i:i+1])[0][0]

        current_char_count = sum(len(s) for s in current_chunk)

        meets_min_sentences = len(current_chunk) >= min_sentences
        meets_min_chars = current_char_count >= min_chars
        semantically_different = sim < threshold
        too_long_sentences = len(current_chunk) >= max_sentences
        too_long_chars = current_char_count >= max_chunk_chars

        force_split = too_long_sentences or too_long_chars

        conditional_semantic_split = semantically_different and meets_min_sentences and meets_min_chars

        should_split = force_split or conditional_semantic_split

        if should_split:
            chunks.append(" ".join(current_chunk))
            current_chunk = [sentences[i]]
        else:
            current_chunk.append(sentences[i])

    if current_chunk:
        chunks.append(" ".join(current_chunk))

    return chunks

In [42]:
def get_word_weights(doc, vectorizer):
  doc_tfidf = vectorizer.transform([doc])
  feature_names = vectorizer.get_feature_names_out()

  df = pd.DataFrame(doc_tfidf[0].T.todense(),
                    index=feature_names,
                    columns=["tfidf"])

  ret = df.sort_values(by="tfidf", ascending=False)

  return ret.head(3).index.tolist()

In [43]:
def get_chunks_for_df(df, process_artworks, min_sentences=1):
  chunks_arr = []

  # Add tqdm to the iterrows loop for a progress bar
  for idx, row in tqdm(df.iterrows(), total=len(df), desc="Chunking texts"):
    if (row["text"] is not None):
      if (row["is_artwork"] and not process_artworks):
        # skip processing for artwork titles
        chunks_arr.append({
            "source_idx": row["source_idx"],
            "text": row["text"],
            "is_artwork": row["is_artwork"]
        })
      else:
        chunks = semantic_chunk(row["text"], 0.75, min_sentences)
        for chunk in chunks:
            chunks_arr.append({
                "source_idx": row["source_idx"],
                "text": chunk,
                "is_artwork": row["is_artwork"]
            })


  chunks_df = pd.DataFrame(chunks_arr)
  return chunks_df

In [44]:
def semantic_chunk(text, threshold=0.75, min_sentences=1, min_chars=100, max_sentences=3, max_chunk_chars=300):
    # replace double new lines with an explicit marker  to force a chunk split.
    processed_text = re.sub(r'\n\n+', '\n<PARAGRAPH_SPLIT_MARKER>\n', text)
    doc = nlp(processed_text)

    sentences_raw = [sent.text.strip() for sent in doc.sents if sent.text.strip()]

    if not sentences_raw:
        return []

    sentences_to_embed_flat = []
    original_idx_to_flat_indices = []

    current_flat_idx = 0
    for s_raw_text in sentences_raw:
        if '<PARAGRAPH_SPLIT_MARKER>' in s_raw_text:
            # if the sentence contains the marker, split it to extract actual text parts and discard the text
            parts = [p.strip() for p in s_raw_text.split('<PARAGRAPH_SPLIT_MARKER>') if p.strip()]
            if parts:
                original_idx_to_flat_indices.append((current_flat_idx, len(parts)))
                sentences_to_embed_flat.extend(parts)
                current_flat_idx += len(parts)
            else:
                original_idx_to_flat_indices.append((-1, 0))
        else:
            # add clean sentences to be embedded
            original_idx_to_flat_indices.append((current_flat_idx, 1))
            sentences_to_embed_flat.append(s_raw_text)
            current_flat_idx += 1

    if not sentences_to_embed_flat:
        return []

    embeddings_flat = model.encode(
        [f"search_document: {s}" for s in sentences_to_embed_flat],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    chunks = []
    current_chunk_sentences = []
    current_chunk_embeddings = []

    for i, sentence_raw_text in enumerate(sentences_raw):
        start_flat_idx, num_flat_sentences = original_idx_to_flat_indices[i]

        # for forced split points with no actual text
        if start_flat_idx == -1:
            if current_chunk_sentences:
                chunks.append(" ".join(current_chunk_sentences))
                current_chunk_sentences = []
                current_chunk_embeddings = []
            continue

        # iterate over extracted clean sentences
        for j in range(num_flat_sentences):
            sentence_to_process = sentences_to_embed_flat[start_flat_idx + j]
            embedding_to_process = embeddings_flat[start_flat_idx + j]

            prospective_chunk_len_sentences = len(current_chunk_sentences) + 1
            prospective_chunk_len_chars = sum(len(s) for s in current_chunk_sentences) + len(sentence_to_process)

            force_max_split = prospective_chunk_len_sentences > max_sentences or prospective_chunk_len_chars > max_chunk_chars

            semantically_different_split = False
            if current_chunk_sentences:
                current_char_count = sum(len(s) for s in current_chunk_sentences)
                meets_min_sentences_for_sem = len(current_chunk_sentences) >= min_sentences
                meets_min_chars_for_sem = current_char_count >= min_chars

                chunk_embedding = np.mean(current_chunk_embeddings, axis=0, keepdims=True)
                sim = cosine_similarity(chunk_embedding, embedding_to_process.reshape(1, -1))[0][0]
                semantically_different_split = sim < threshold and meets_min_sentences_for_sem and meets_min_chars_for_sem

            should_split = False
            if current_chunk_sentences and (force_max_split or semantically_different_split):
                should_split = True

            if should_split:
                chunks.append(" ".join(current_chunk_sentences))
                current_chunk_sentences = [sentence_to_process]
                current_chunk_embeddings = [embedding_to_process]
            else:
                current_chunk_sentences.append(sentence_to_process)
                current_chunk_embeddings.append(embedding_to_process)

    # add the current sentences if not empty
    if current_chunk_sentences:
        chunks.append(" ".join(current_chunk_sentences))

    return chunks

# Prep data

In [45]:
# get all exhibition text
exhibitions_df['full_text'] = exhibitions_df['name'].fillna('') + ". " + exhibitions_df['description'].fillna('')

In [46]:
# chunk artist texts
ar_texts = get_chunks_for_df(artist_texts_df, False, 2)

Chunking texts:   0%|          | 0/584 [00:00<?, ?it/s]

In [47]:
print(len(ar_texts))
ar_texts.head()

7576

  source_idx                                               text  is_artwork
0       AT01  That’s a great question, but also a rabbit hol...       False
1       AT01  I wanted to directly challenge previous assert...       False
2       AT01  I think of my work as an organism that fluctua...       False
3       AT01  I’ve always been interested in the shared real...       False
4       AT01  In previous works, I mined the generic for fou...       False

In [48]:
# chunk inst texts
inst_texts = get_chunks_for_df(institution_texts_df, True, 1)

Chunking texts:   0%|          | 0/338 [00:00<?, ?it/s]

In [49]:
print(len(inst_texts))
inst_texts.head()

846

  source_idx                 text  is_artwork
0       IT01  American, born 1975       False
1       IT02             American       False
2       IT03               female       False
3       IT04  American, born 1975       False
4       IT05             American       False

# Labeling - stop words

In [50]:
new_stop_words = ["biennale", "biennial", "museum", "exhibition", "baratta", "italian", "year", "s", "art", "artist", "th", "arsenale", "tam"]
custom_stop_words = list(sklearn_text.ENGLISH_STOP_WORDS.union(new_stop_words))

In [51]:
# add all the artist first and last names to the stop words list
for idx, row in artists_df.iterrows():
    # split by first and last name
    names = re.split(r'[- ]', row["name"])

    for name in names:
      custom_stop_words.append(name.lower())

# add all locations
for idx, row in exhibitions_df.iterrows():
  locations = re.split(r'[, ]', row["location"])

  for location in locations:
    custom_stop_words.append(location.lower())

In [52]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text.lower())

# Exhibition labels

In [53]:
all_corpus = exhibitions_df['full_text'].tolist()

vectorizer = TfidfVectorizer(preprocessor=remove_numbers, stop_words=custom_stop_words)

tfidf_matrix = vectorizer.fit_transform(all_corpus)

In [54]:
# get word weights for each row in exhibitions
exhibitions_df["labels"] = exhibitions_df.apply(lambda row: get_word_weights(row['full_text'], vectorizer), axis=1)
exhibitions_df["labels"]

0                 [hapa, ancestry, asian]
1                [mixed, asian, american]
2               [citizen, universe, life]
3                 [orient, dis, diaspora]
4             [legacies, asian, american]
5                  [east, asian, chinese]
6       [countries, international, world]
7     [ideologies, global, authoritarian]
8              [korean, english, pacific]
9               [hard, american, america]
10      [portraiture, asian, smithsonian]
11         [ascendancy, agency, personal]
12             [american, asian, chinese]
13           [decade, studio, frameworks]
Name: labels, dtype: object

In [ ]:
# download w labels
exhibitions_df.to_csv('exhibitions_with_labels.csv', index=False)

files.download('exhibitions_with_labels.csv')

# Filter for identity-specific texts

For artists

In [55]:
query_words = [
    # original
    "identity", "persona", "race", "ethnicity", "culture",
    "self", "category", "belonging", "community",
    "ancestry", "generation", "experience", "in-between",

    # mixed race
    "mixed", "multiracial", "biracial", "half", "hyphenated",
    "passing", "blood", "skin", "contradict"

    # diaspora
    "diaspora", "diasporic", "transnational", "immigrant", "migration",
    "displacement", "exile", "homeland", "motherland", "origin",

    # in betweenness
    "liminal", "borderlands", "threshold", "assimilation", "integration",

    # heritage
    "heritage", "roots", "memory", "nostalgia", "home", "tradition",
    "language", "birth", "death", "born", "nationality", "died"

    # visibility
    "otherness", "outsider", "minority", "visibility", "authenticity",
    "representation", "erasure", "recognition", "voice", "truth",
    "invisible", "seen", "silence", "absence"
]

In [56]:
# self relevance query to get first-person testimony about the artist's own experience rather than framing others
self_query = (
    "search_query: speaking in my own voice about who I am — "
    "my mixed heritage, my family's immigration story, growing up caught between cultures, "
    "and how my racial and ethnic identity lives in my body and my life"
)

In [57]:
# density of first person words to filter for speaking about self
def _fp_density(text):
    words = re.findall(r'\b\w+\b', text.lower())
    fp = sum(1 for w in words if w in {'i', 'me', 'my', 'mine', 'myself'})
    return fp / max(len(words), 1)

In [58]:
chunk_embeddings_for_filter = model.encode(
    ["search_document: " + t for t in ar_texts["text"]],
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/237 [00:00<?, ?it/s]

In [62]:
# get identity relevance first
identity_query = "search_query: " + " ".join(query_words)
identity_query_embedding = model.encode(identity_query, convert_to_numpy=True, normalize_embeddings=True)

ar_texts["identity_relevance"] = cosine_similarity([identity_query_embedding], chunk_embeddings_for_filter)[0]

# get self relevance
self_query_embedding = model.encode(self_query, convert_to_numpy=True, normalize_embeddings=True)
ar_texts["self_relevance"] = cosine_similarity([self_query_embedding], chunk_embeddings_for_filter)[0]

# first person density words to tiebreak in some cases
ar_texts["fp_density"] = ar_texts["text"].apply(_fp_density)
fp_norm_cap = 0.15
ar_texts["fp_density_norm"] = (ar_texts["fp_density"] / fp_norm_cap).clip(upper=1.0)

# weigh priority
ar_texts["priority_score"] = (
    ar_texts["identity_relevance"] * 0.35
    + ar_texts["self_relevance"]   * 0.55
    + ar_texts["fp_density_norm"]  * 0.10
)

# per-artist floor + ceiling using priority score
THRESHOLD = 0.58   # for identity_relevance to filter to topic
MIN_QUOTES = 3
MAX_QUOTES = 12

source_to_artist = artist_texts_df.set_index('source_idx')['artist'].to_dict()
ar_texts['artist_id'] = ar_texts['source_idx'].map(source_to_artist)

def filter_artist_quotes(group):
    above = group[group['identity_relevance'] >= THRESHOLD]
    if len(above) >= MIN_QUOTES:
        return above.nlargest(MAX_QUOTES, 'priority_score')
    else:
        return group.nlargest(MIN_QUOTES, 'priority_score')

non_artwork = ar_texts[ar_texts['is_artwork'] == False]
artworks    = ar_texts[ar_texts['is_artwork'] == True]

filtered_text = non_artwork.groupby('artist_id', group_keys=False).apply(filter_artist_quotes)
filtered_ar_texts = pd.concat([filtered_text, artworks]).reset_index(drop=True)

print(f"Rows remaining: {len(filtered_ar_texts)}")
print(f"\nArtist text chunks per artist:\n{filtered_text.groupby('artist_id').size().sort_values()}")

Rows remaining: 680

Artist text chunks per artist:
artist_id
0      3
8      3
10     3
17     3
5      4
27     4
21     4
1      4
2      7
28     8
19     9
25    10
12    10
6     11
7     12
4     12
15    12
14    12
13    12
11    12
9     12
3     12
18    12
16    12
23    12
22    12
20    12
24    12
26    12
29    12
dtype: int64

/tmp/ipykernel_1328/3590360449.py:41: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  filtered_text = non_artwork.groupby('artist_id', group_keys=False).apply(filter_artist_quotes)

In [ ]:
texts_only = filtered_ar_texts[filtered_ar_texts["is_artwork"] == False]
texts_only.to_csv('ar_texts_filtered.csv', index=False)
files.download('ar_texts_filtered.csv')

# Embed all texts

For artists

In [63]:
ar_texts = filtered_ar_texts

In [64]:
ar_texts_arr = ["clustering: " + t for t in ar_texts["text"].tolist()]

# embed
ar_embeddings = model.encode(
    ar_texts_arr,
    batch_size=64,
    convert_to_tensor=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

ar_embeddings_np = ar_embeddings.cpu().numpy()

Batches:   0%|          | 0/11 [00:00<?, ?it/s]

For institutions

In [65]:
inst_texts_arr = ["clustering: " + t for t in inst_texts["text"].tolist()]

# embed
inst_embeddings = model.encode(
    inst_texts_arr,
    batch_size=64,
    convert_to_tensor=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

inst_embeddings_np = inst_embeddings.cpu().numpy()

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

# Build lookups

In [66]:
artist_texts_source_idx_map = artist_texts_df.set_index('source_idx')
institution_texts_source_idx_map = institution_texts_df.set_index('source_idx')

artworks_source_idx_map = artworks_df.set_index('id')

In [67]:
def map_metadata(row, mode):
    artist_id = np.nan
    institution_id = np.nan

    if mode == 'artist':
      source_idx_map = artist_texts_source_idx_map
    else:
      source_idx_map = institution_texts_source_idx_map

    if row['is_artwork']:
        artwork_row = artworks_source_idx_map.loc[row['source_idx']]
        artist_id = artwork_row['artist']
        institution_id = artwork_row['institution']
    else:
        artist_id = source_idx_map.loc[row['source_idx'], 'artist']
        if mode != 'artist':
          institution_id = source_idx_map.loc[row['source_idx'], 'institution']

    return pd.Series({'artist_id': artist_id, 'institution_id': institution_id})

In [68]:
artist_id_to_name = artists_df.set_index("id")["name"].to_dict()
inst_id_to_name = institutions_df.set_index("id")["name"].to_dict()

ar_lookup_df = ar_texts[["text", "source_idx", "is_artwork"]].copy()

ar_lookup_df[['artist_id', 'institution_id']] = ar_lookup_df.apply(lambda x: map_metadata(x, 'artist'), axis=1)

ar_lookup_df['artist_id'] = ar_lookup_df['artist_id'].astype(pd.Int64Dtype())
ar_lookup_df['institution_id'] = ar_lookup_df['institution_id'].astype(pd.Int64Dtype())

# for testing, map to names to see accuracy
ar_lookup_df['artist_name'] = ar_lookup_df['artist_id'].map(artist_id_to_name)
ar_lookup_df['institution_name'] = ar_lookup_df['institution_id'].map(inst_id_to_name)

ar_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"So, I’m still a struggling artist—at least in ...",AT53,False,0,<NA>,Isamu Noguchi,NaN
1,So I don’t have much faith in myself as a kind...,AT54,False,0,<NA>,Isamu Noguchi,NaN
2,It’s what keeps me going.,AT53,False,0,<NA>,Isamu Noguchi,NaN
3,The important thing is that I wasn’t intereste...,AT01,False,1,<NA>,Amanda Ross-Ho,NaN
4,My practice originates in the act of negotiati...,AT04,False,1,<NA>,Amanda Ross-Ho,NaN
...,...,...,...,...,...,...,...
675,Belly Painting: Prussian Blue,W405,True,12,7,Byron Kim,National Gallery of Art
676,Untitled,W406,True,29,7,Hung Liu,National Gallery of Art
677,Post-Age,W407,True,29,7,Hung Liu,National Gallery of Art
678,Seoul Home – Inverted,W408,True,6,7,Do Ho Suh,National Gallery of Art
679,Prison Bunk Beds,W409,True,10,7,Martin Wong,National Gallery of Art

In [69]:
inst_lookup_df = inst_texts[["text", "source_idx", "is_artwork"]].copy()

inst_lookup_df[['artist_id', 'institution_id']] = inst_lookup_df.apply(lambda x: map_metadata(x, 'institution'), axis=1)

inst_lookup_df['artist_id'] = inst_lookup_df['artist_id'].astype(pd.Int64Dtype())
# inst_lookup_df['institution_id'] = inst_lookup_df['institution_id'].astype(pd.Int64Dtype())

# add names for testing
inst_lookup_df['artist_name'] = inst_lookup_df['artist_id'].map(artist_id_to_name)
inst_lookup_df['institution_name'] = inst_lookup_df['institution_id'].map(inst_id_to_name)

inst_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"American, born 1975",IT01,False,1,0,Amanda Ross-Ho,Museum of Modern Art
1,American,IT02,False,1,0,Amanda Ross-Ho,Museum of Modern Art
2,female,IT03,False,1,0,Amanda Ross-Ho,Museum of Modern Art
3,"American, born 1975",IT04,False,2,0,Laurel Nakadate,Museum of Modern Art
4,American,IT05,False,2,0,Laurel Nakadate,Museum of Modern Art
...,...,...,...,...,...,...,...
841,The facial features are partially visible in p...,W404,True,21,7,Alfonso Ossorio,National Gallery of Art
842,They are not shown wearing any jewelry or hold...,W404,True,21,7,Alfonso Ossorio,National Gallery of Art
843,The image shows a composition of lines and sha...,W406,True,29,7,Hung Liu,National Gallery of Art
844,"In the left oval, there is a pattern resemblin...",W406,True,29,7,Hung Liu,National Gallery of Art
845,The juxtaposition of familiar shapes suggests ...,W406,True,29,7,Hung Liu,National Gallery of Art

In [70]:
inst_lookup_df

,text,source_idx,is_artwork,artist_id,institution_id,artist_name,institution_name
0,"American, born 1975",IT01,False,1,0,Amanda Ross-Ho,Museum of Modern Art
1,American,IT02,False,1,0,Amanda Ross-Ho,Museum of Modern Art
2,female,IT03,False,1,0,Amanda Ross-Ho,Museum of Modern Art
3,"American, born 1975",IT04,False,2,0,Laurel Nakadate,Museum of Modern Art
4,American,IT05,False,2,0,Laurel Nakadate,Museum of Modern Art
...,...,...,...,...,...,...,...
841,The facial features are partially visible in p...,W404,True,21,7,Alfonso Ossorio,National Gallery of Art
842,They are not shown wearing any jewelry or hold...,W404,True,21,7,Alfonso Ossorio,National Gallery of Art
843,The image shows a composition of lines and sha...,W406,True,29,7,Hung Liu,National Gallery of Art
844,"In the left oval, there is a pattern resemblin...",W406,True,29,7,Hung Liu,National Gallery of Art
845,The juxtaposition of familiar shapes suggests ...,W406,True,29,7,Hung Liu,National Gallery of Art

# Helpers to cluster for n

In [71]:
def run_clustering_and_evaluate(embeddings, n_clusters, sample_weight=None):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init="auto")
    cluster_labels = kmeans.fit_predict(embeddings, sample_weight=sample_weight)

    sc = kmeans.score(embeddings, sample_weight=sample_weight)
    distance_sc = distance_score(embeddings, cluster_labels)
    silhouette_sc = silhouette_score(embeddings, cluster_labels)
    balance_sc = balance_score(cluster_labels)

    print(f"\n{'='*80}")
    print(f"FOR NUM CLUSTERS {n_clusters} --------------------")
    print("score: ", sc)
    print("distance score: ", distance_sc)
    print("silhouette score: ", silhouette_sc)
    print("balance score: ", balance_sc)

    return kmeans, cluster_labels

In [72]:
def calculate_distances(embeddings_np, kmeans):
    centers = kmeans.cluster_centers_
    all_distances = euclidean_distances(embeddings_np, centers)

    return all_distances

In [ ]:
def extract_cluster_keywords(df_source, cluster_labels, n_clusters, stop_words):
      temp_df = df_source.copy()                                                                                                                                                                             
      temp_df["cluster"] = cluster_labels
      cluster_texts = []                                                                                                                                                                                     
      for c in range(n_clusters):                           
          mask = temp_df["cluster"] == c                                                                                                                                                                     
          combined = " ".join(temp_df.loc[mask, "text"].tolist())
          cluster_texts.append(combined)                                                                                                                                                                     
      vectorizer = TfidfVectorizer(preprocessor=remove_numbers, stop_words=stop_words, token_pattern=r'\b\w*[a-zA-Z]\w*\b', max_features=1000, ngram_range=(1,1))
      tfidf_matrix = vectorizer.fit_transform(cluster_texts)                                                                                                                                                 
      feature_names = vectorizer.get_feature_names_out()                                                                                                                                                     
      top_n = 5                                                                                                                                                                                              
      cluster_keywords = {}                                                                                                                                                                                  
      for c in range(n_clusters):                           
          top_indices = np.argsort(tfidf_matrix[c].toarray()[0])[::-1][:top_n]                                                                                                                               
          keywords = [feature_names[i] for i in top_indices]
          kw_embeddings = model.encode(                                                                                                                                                                      
              ["search_document: " + kw for kw in keywords],                                                                                                                                                 
              convert_to_numpy=True, normalize_embeddings=True
          )                                                                                                                                                                                                  
          kw_sims = cosine_similarity([identity_query_embedding], kw_embeddings)[0]
          keywords = [kw for _, kw in sorted(zip(kw_sims, keywords), reverse=True)]                                                                                                                          
          cluster_keywords[str(c)] = keywords
      return cluster_keywords

In [74]:
def get_cluster_results_df(df_source, cluster_labels, all_distances, n_clusters):
    own_center_distances = all_distances[range(len(cluster_labels)), cluster_labels]

    masked = all_distances.copy()
    masked[range(len(cluster_labels)), cluster_labels] = np.inf
    closest_other_cluster = np.argmin(masked, axis=1)
    closest_other_cluster_distance = masked[range(len(cluster_labels)), closest_other_cluster]

    results_df = pd.DataFrame({
        "point":                 range(len(cluster_labels)),
        "cluster":               cluster_labels,
        "distance_to_center":    own_center_distances,
        "text":            df_source["text"].values,
        "artist_id":        df_source["artist_id"],
        "is_artwork":      df_source["is_artwork"],
        "source_idx":            df_source["source_idx"].values
    })

    for c in range(n_clusters):
      results_df[f"dist_to_cluster_{c}"] = all_distances[:, c]

    if 'institution_id' in df_source.columns:
        results_df["institution_id"] = df_source["institution_id"].values

    if 'artist_name' in df_source.columns:
        results_df["artist_name"] = df_source["artist_name"].values

    return results_df

In [76]:
ARTWORK_WEIGHT = 0.25  # weigh artwork titles and descriptions less in calculating centers

def get_all_clusters(fname, embeddings, lookups, n_clusters):
    weights = np.where(lookups["is_artwork"].values, ARTWORK_WEIGHT, 1.0)
    all_json_data = []

    for k in range(8, n_clusters):
        kmeans_model, labels = run_clustering_and_evaluate(embeddings, k, sample_weight=weights)

        distances = calculate_distances(embeddings, kmeans_model)

        keywords_dict = extract_cluster_keywords(lookups, labels, k, custom_stop_words)

        results_df = get_cluster_results_df(lookups, labels, distances, k)

        cluster_list = []
        for c in range(k):
            c_str = str(c)
            cluster_data = results_df[results_df['cluster'] == c].to_dict(orient='records')
            cluster_list.append({
                "key": c_str,
                "keywords": keywords_dict.get(c_str, []),
                "data": cluster_data
            })

        all_json_data.append({
            "n": k,
            "clusters": cluster_list
        })

    filename = fname + '.json'
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(all_json_data, f, indent=4, ensure_ascii=False)

    files.download(filename)

# Cluster by n

In [80]:
get_all_clusters('inst_clusters', inst_embeddings_np, inst_lookup_df, 31)

================================================================================
FOR NUM CLUSTERS 8 --------------------
score:  -127.33401489257812
distance score:  0.45386887
silhouette score:  0.061033543
balance score:  0.596757852077001

================================================================================
FOR NUM CLUSTERS 9 --------------------
score:  -124.91783905029297
distance score:  0.4529143
silhouette score:  0.060398784
balance score:  0.6635638297872342

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 10 --------------------
score:  -123.42989349365234
distance score:  0.45759043
silhouette score:  0.06060606
balance score:  0.654320987654321

================================================================================
FOR NUM CLUSTERS 11 --------------------
score:  -121.60816192626953
distance score:  0.45973635
silhouette score:  0.05823645
balance score:  0.7018912529550827

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 12 --------------------
score:  -119.04835510253906
distance score:  0.45675024
silhouette score:  0.06128791
balance score:  0.6640876853642812

================================================================================
FOR NUM CLUSTERS 13 --------------------
score:  -118.1842041015625
distance score:  0.46137264
silhouette score:  0.060896114
balance score:  0.6699172576832151

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 14 --------------------
score:  -117.6050033569336
distance score:  0.46250623
silhouette score:  0.056452047
balance score:  0.6813966175668303

================================================================================
FOR NUM CLUSTERS 15 --------------------
score:  -115.39794158935547
distance score:  0.45960435
silhouette score:  0.062406898
balance score:  0.6752786220871327

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 16 --------------------
score:  -114.55023193359375
distance score:  0.4607252
silhouette score:  0.06024869
balance score:  0.6877856579984238

================================================================================
FOR NUM CLUSTERS 17 --------------------
score:  -113.30238342285156
distance score:  0.4609744
silhouette score:  0.06470996
balance score:  0.7162381796690307

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 18 --------------------
score:  -112.06214904785156
distance score:  0.45671648
silhouette score:  0.06493551
balance score:  0.7108886107634544

================================================================================
FOR NUM CLUSTERS 19 --------------------
score:  -111.06416320800781
distance score:  0.4582234
silhouette score:  0.069589555
balance score:  0.7257026530076176

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 20 --------------------
score:  -110.79418182373047
distance score:  0.45046014
silhouette score:  0.06682393
balance score:  0.7023765086475053

================================================================================
FOR NUM CLUSTERS 21 --------------------
score:  -109.14091491699219
distance score:  0.45689747
silhouette score:  0.075701885
balance score:  0.6921985815602836

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 22 --------------------
score:  -108.81541442871094
distance score:  0.45001096
silhouette score:  0.069694854
balance score:  0.6559720815039963

================================================================================
FOR NUM CLUSTERS 23 --------------------
score:  -107.5118179321289
distance score:  0.4467979
silhouette score:  0.07164414
balance score:  0.6755856436707501

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 24 --------------------
score:  -107.05128479003906
distance score:  0.4426781
silhouette score:  0.07010388
balance score:  0.6500154178230034

================================================================================
FOR NUM CLUSTERS 25 --------------------
score:  -106.38719940185547
distance score:  0.4434106
silhouette score:  0.071086966
balance score:  0.6659771473601261

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 26 --------------------
score:  -104.70870208740234
distance score:  0.43663022
silhouette score:  0.07554997
balance score:  0.6426477541371158

================================================================================
FOR NUM CLUSTERS 27 --------------------
score:  -104.37812042236328
distance score:  0.44120622
silhouette score:  0.07637824
balance score:  0.6640752864157119

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 28 --------------------
score:  -103.44837188720703
distance score:  0.44215488
silhouette score:  0.07727423
balance score:  0.6765607214779792

================================================================================
FOR NUM CLUSTERS 29 --------------------
score:  -103.0525894165039
distance score:  0.44167513
silhouette score:  0.075283535
balance score:  0.6803444782168186

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 30 --------------------
score:  -102.38956451416016
distance score:  0.44272307
silhouette score:  0.07589513
balance score:  0.6786500366837858

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

In [81]:
get_all_clusters('ar_clusters', ar_embeddings_np, ar_lookup_df, 31)

================================================================================
FOR NUM CLUSTERS 8 --------------------
score:  -103.83759307861328
distance score:  0.5099504
silhouette score:  0.019418515
balance score:  0.5747899159663865

================================================================================
FOR NUM CLUSTERS 9 --------------------
score:  -102.94357299804688
distance score:  0.50827146
silhouette score:  0.017981578
balance score:  0.5707720588235294

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 10 --------------------
score:  -101.68531799316406
distance score:  0.5055375
silhouette score:  0.029778043
balance score:  0.6486928104575163

================================================================================
FOR NUM CLUSTERS 11 --------------------
score:  -101.22711181640625
distance score:  0.5057914
silhouette score:  0.030709455
balance score:  0.6354411764705883

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 12 --------------------
score:  -100.02408599853516
distance score:  0.5000294
silhouette score:  0.031437308
balance score:  0.6235294117647059

================================================================================
FOR NUM CLUSTERS 13 --------------------
score:  -99.20714569091797
distance score:  0.49840206
silhouette score:  0.03064053
balance score:  0.6138480392156863

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 14 --------------------
score:  -97.99089050292969
distance score:  0.49202675
silhouette score:  0.03452666
balance score:  0.6242081447963801

================================================================================
FOR NUM CLUSTERS 15 --------------------
score:  -97.7352523803711
distance score:  0.481242
silhouette score:  0.033805355
balance score:  0.6397058823529412

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 16 --------------------
score:  -97.21115112304688
distance score:  0.4818574
silhouette score:  0.03453315
balance score:  0.6329411764705882

================================================================================
FOR NUM CLUSTERS 17 --------------------
score:  -96.60491180419922
distance score:  0.48127523
silhouette score:  0.034521636
balance score:  0.6187500000000001

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 18 --------------------
score:  -96.03026580810547
distance score:  0.47862482
silhouette score:  0.036149032
balance score:  0.6143598615916955

================================================================================
FOR NUM CLUSTERS 19 --------------------
score:  -95.4991226196289
distance score:  0.4710966
silhouette score:  0.03611493
balance score:  0.6062908496732027

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 20 --------------------
score:  -94.9898910522461
distance score:  0.47088987
silhouette score:  0.040394776
balance score:  0.6300309597523219

================================================================================
FOR NUM CLUSTERS 21 --------------------
score:  -93.43645477294922
distance score:  0.47071758
silhouette score:  0.054275833
balance score:  0.6472058823529412

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 22 --------------------
score:  -92.34293365478516
distance score:  0.45814008
silhouette score:  0.06426193
balance score:  0.6588235294117647

================================================================================
FOR NUM CLUSTERS 23 --------------------
score:  -92.07018280029297
distance score:  0.4569559
silhouette score:  0.064016126
balance score:  0.6491978609625668

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 24 --------------------
score:  -91.59211730957031
distance score:  0.4374373
silhouette score:  0.06409805
balance score:  0.6419437340153453

================================================================================
FOR NUM CLUSTERS 25 --------------------
score:  -91.25450134277344
distance score:  0.43755513
silhouette score:  0.06424694
balance score:  0.6338848039215688

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 26 --------------------
score:  -90.64368438720703
distance score:  0.4377963
silhouette score:  0.06503947
balance score:  0.6264705882352941

================================================================================
FOR NUM CLUSTERS 27 --------------------
score:  -90.4093246459961
distance score:  0.43601662
silhouette score:  0.06380869
balance score:  0.6242081447963801

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 28 --------------------
score:  -89.5155029296875
distance score:  0.4235327
silhouette score:  0.079863325
balance score:  0.6381263616557735

================================================================================
FOR NUM CLUSTERS 29 --------------------
score:  -89.0882797241211
distance score:  0.42668885
silhouette score:  0.08363424
balance score:  0.6666491596638655

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

================================================================================
FOR NUM CLUSTERS 30 --------------------
score:  -88.62420654296875
distance score:  0.42514536
silhouette score:  0.082682826
balance score:  0.6632860040567952

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['c', 'd'] not in stop_words.
  warnings.warn(

## Combine artist-specific texts from both sources

In [79]:
combined_artist_data = []

ar_data_for_combine = ar_lookup_df.copy()
ar_data_for_combine = ar_data_for_combine[['artist_id', 'institution_id', 'is_artwork', 'source_idx', 'text']]

inst_data_for_combine = inst_lookup_df.copy()
inst_data_for_combine = inst_data_for_combine[['artist_id', 'institution_id', 'is_artwork', 'source_idx', 'text']]

all_artist_points_df = pd.concat([ar_data_for_combine, inst_data_for_combine], ignore_index=True)

display(all_artist_points_df.head())

all_artist_points_df.to_csv('all_artist_combined_texts.csv')
files.download('all_artist_combined_texts.csv')

,artist_id,institution_id,is_artwork,source_idx,text
0,0,<NA>,False,AT53,"So, I’m still a struggling artist—at least in ..."
1,0,<NA>,False,AT54,So I don’t have much faith in myself as a kind...
2,0,<NA>,False,AT53,It’s what keeps me going.
3,1,<NA>,False,AT01,The important thing is that I wasn’t intereste...
4,1,<NA>,False,AT04,My practice originates in the act of negotiati...